### ISSUE TITLE
<basedir>/index.php/backend was not found on this server.

### ISSUE THREAD

**Issue by idovitz** [alextselegidis/easyappointments#1]
After install following error:
<basedir>/index.php/backend was not found on this server.

mod_rewrite is installed on debian wheezy apache 2.2 / php 5.4 / mysql 5.5

**Comment by alextselegidis** [comment]
Any information at the error logs? That seems to be a server configuration issue and other users seem to have similar problems. E!A is using the CodeIgniter URL rewriting method so I would like feedback in order to fix these issues.

**Comment by bkrajendra** [comment]
I was having similar problem related to URL not being recognised
I followed this guide... 
https://github.com/bcit-ci/CodeIgniter/wiki/Godaddy-Installation-Tips
everything started working.
Except appointment time problem is still not  resolved.

**Comment by pguridi** [comment]
I can confirm this issue, I followed all the installation steps, and I'm getting the same error.
Tried on Ubuntu 14.04 LTS, with Mysql and apache with mod_rewrite enabled.
Maybe there is something missing on the installation notes?. On which platform (or with which configuration) is probed to work out of the box?

**Comment by bkrajendra** [comment]
Its the best appointment management system I've ever seen but URL routing is very poorly handled in this project. Some route work with "/" ( http://domain.com/) at the end of path and some don't.
There are some framework like php Laravel5, which handles these issue on different platform very effectively. It'll be nice if this project is ported to Laravel5.

**Comment by atenhotep** [comment]
I am essentially having the same problem.  On my shared hosting, routing to the backend just doesn't work.  The changes suggested above on GoDaddy do not help.  I'd love to explore this project deeper to see if it works for my purposes, instead of rolling my own, but I can't get it working.  

I am also finding myself unable to actually add things to the backend, if explicitly reach the backend by inserting '/index.php?' after the base directory and before the route.  I am bummed!  It looks like a great project.

**Comment by bkrajendra** [comment]
@atenhotep , if you are using code from this github repo, you might face many issues.
As per the author of this code use release from the site only. Github repo is not stable and might lead to many problem. 

The suggestion to author will be to follow single method or rule for routes. Decide whether to add "/" after base url, as if you're adding it you have to take care that it should not get added latter in any url.
Also always use internal codeigniter methods to get base URL, instead of telling user to enter it. 
I hope I'm right!!!

At my side everything is working fine, as I've removed or added few "/" in Ajax JS files. I'll suggest you all to check ur Chrome console for more info to solve routing issue on this repo.

**Comment by calvinlloyd** [comment]
@bkrajendra can you share any more insight on how you fixed this routing issue?...maybe specific places where you added the /'s

Or can you share the final ajax js files?

**Comment by alextselegidis** [comment]
Hello, I am currently switching the urls to work without the mod_rerwite. You can get the code from here (github) and try it. 

Could be very unstable though, but you will not have the routing problems. Stay tuned for more new commits and updates.

**Comment by atenhotep** [comment]
Thanks for keeping me in the loop. I've been busy with
other things, but will be checking it out soon. 

In Gratitude, 

iam (ishmael aylwin mc intosh) 

On 2015-06-25 13:57, Alex Tselegidis wrote: 

> Closed #1 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1] https://github.com/alextselegidis/easyappointments/issues/1
[2]
https://github.com/alextselegidis/easyappointments/issues/1#event-340391123

**Comment by atenhotep** [comment]
I had problems similar to the people reporting issues about clicking
on install being a noop. I was using a clone of the HEAD of the repo. 

I will have to look into this more later. I did notice that it didn't
seem 
like I was picking up the CSS correctly, because the form looked a mess.

None of the issues that people reported as fixing this issue for them 
worked for me, but I have done no digging into my actual installation
as yet. 

Thanks Again! I'd love to get it working, although my immediate 
use for it has been resolved. 

In Gratitude, 

iam (ishmael aylwin mc intosh) 

On 2015-06-25 13:57, Alex Tselegidis wrote: 

> Closed #1 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1] https://github.com/alextselegidis/easyappointments/issues/1
[2]
https://github.com/alextselegidis/easyappointments/issues/1#event-340391123
