### ISSUE TITLE
Attendants number in secretary view or admin view.

### ISSUE THREAD

**Issue by bicolorman** [alextselegidis/easyappointments#1006]
I have configured to only 1 Attendants Number,  from booking page all is ok, but if I make appointment from secretary view or admin view , I can book many attendants in this view. Not only one,  and can change the duration.

**Comment by alextselegidis** [comment]
Hello! 

That's right because backend users do not have limitations on how to schedule their plans. 

Have them use the booking page if you want to see real time availability. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bicolorman** [comment]
Hi.
But the is not correct that the secretary can schedule without control, she
can make a lot of errors. can I only for secretary view limit the
participant o the behavior. ?
Regards,

*Oscar Dario Gonzalez Eslava*
The only way to perform to your ultimate potential is self-motivation, hard
work, a positive attitude
------------------------------
