### ISSUE TITLE
I have problem when setup Easy Appointment

### ISSUE THREAD

**Issue by TheRules09** [alextselegidis/easyappointments#1007]
This Message appear when I click Install

The operation could not complete due to unexpected issues.
The migration class "Migration_Specific_calendar_sync" is missing an "up" method.

Please help me, Thank You

![image](https://user-images.githubusercontent.com/78903205/107619152-b0f58100-6c8d-11eb-8429-467391754bb9.png)

**Comment by jamesgrogantech** [comment]
I also have this issue

**Comment by alextselegidis** [comment]
Hello! 

This seems to be an issue with PHP 8 and some vendor dependency of the project. 

Easy!Appointments 1.4.2 will be released soon, supporting the new PHP version. 

Till then you could temporarily downgrade to PHP 7.4 and perform the installation. 

See https://github.com/alextselegidis/easyappointments/issues/993

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I did some search to see where the problem comes from and it is an issue with CodeIgniter. 

Here's the actual fix you can on your own: 

https://github.com/bcit-ci/CodeIgniter/commit/0925b5099919300a239909588351a6482c5e792d

The new Easy!Appointments release will be released after the new CodeIgniter 3 version is out. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
