### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by Lauflust** [alextselegidis/easyappointments#1015]
The date format for the year is incorrect. There are only 3 times a Y.

https://github.com/alextselegidis/easyappointments/blob/2512159285d47ff4e41b6c62633a87c42e8702b0/assets/js/backend_calendar_table_view.js#L757

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting, we have already detected the issue and it will be fixed with the upcoming 1.4.2 

https://github.com/alextselegidis/easyappointments/pull/989/commits/9c99223cb369f8b1d5e2ca71b486df0fe9c8f65e

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
