### ISSUE TITLE
Enhancement: Add a mode where the agenda is only in open time slot

### ISSUE THREAD

**Issue by G-eos** [alextselegidis/easyappointments#1031]
Hello,

Thanks for this software, I would like to have the possibility to have an agenda by default with no time slot available and to open case by case for each time slot (without repetition).

I do not find how to do this, I think it could be a good enhancement. Thanks !

**Comment by alextselegidis** [comment]
Hello! 

With Easy!Appointments 1.4 working plan exceptions got introduced so that you can define arbitrary schedules for the providers. 

Check out this article: 

https://easyappointments.org/2021/01/26/working-plan-exceptions-explained/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
