### ISSUE TITLE
typo in backend_calendar_default_view.js and backend_calendar_default_view_min.js

### ISSUE THREAD

**Issue by verdieping7** [alextselegidis/easyappointments#1035]
typo alert!

unavilable instead of unavailable

dont know the line number :)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this!

This is already fixed in 1.4.1, so please make sure you are using the latest version.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
