### ISSUE TITLE
UI tweaks (reset / delete buttons)

### ISSUE THREAD

**Issue by johanla0** [alextselegidis/easyappointments#1036]
Propose tweaks to improve UI

- [x] ```button #delete-customer``` change class to ```btn-outline-danger```
- [x] ```button #delete-service``` change class to ```btn-outline-danger```
- [x] ```button #delete-provider``` change class to ```btn-outline-danger```
- [x] ```button #delete-secretary``` change class to ```btn-outline-danger```
- [x] ```button #delete-admin``` change class to ```btn-outline-danger```
- [x] ```button #reset-working-plan``` change class to ```btn-danger```

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the suggestions!

Marking removal actions in red makes much sense of course but Easy!Appointments follows or more minimalistic approach where on group of actions there's only one action highlighted and that's the most commonly used or the primary one, so that users can easily find it. 

For that the removal icons will still stay for now at least as secondary options. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
