### ISSUE TITLE
No changes being saved.

### ISSUE THREAD

**Issue by AklElie** [alextselegidis/easyappointments#1051]
Hi,

I update my version to latest but whatever changes i try to make in backend like creating a user or editing a user or editing anything upon clicking save it says saved successfully on whatever task it is, but actually nothing is being saved if i click back into it, it shows unchanged or unsaved settings.

i installed a new machine fresh and followed all instruction but stuck at same place. checked the storage/logs for errors no errors at all.

Another issue is my storage/session folder got accumulated to to 25GB from my WAF if there's a way to stop the session files from storing that would be nice.

**Comment by alextselegidis** [comment]
Hello! 

I understand that you run the application behind a CDN or WAF right? Those are great but they may have unexpected side effects to the operation of the website, such as: 

> try to make in backend like creating a user or editing a user or editing anything upon clicking save it says saved successfully on whatever task it is, but actually nothing is being saved

At this point I would suggest you to try a clean installation on a local server or some other environment that is not using the same setup so that you can isolate the problems and fix them one by one. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
