### ISSUE TITLE
Hot to manage users and Authentication?

### ISSUE THREAD

**Issue by VladimirMitso** [alextselegidis/easyappointments#1053]
Hi. On my current project I'm using Flutter as frontend and Firebase as backend. I have requirement to use this tool for booking meetings. They send me base url and bearer token. As I understand this is token for admin account and using it I can access all data. What I am trying to achieve is to have some kind of Authentication and to manage users. 
    
For example:
- create `customer` account for each user
- have different bearer tokens for different users
- let users to see only their own appointments
- don't let users in any case see others' appointments

Is there a way to do something like this?

**Comment by alextselegidis** [comment]
Hello! 

For the interaction with the API it is true that the only thing you need is the bearer token, which will allow you to access all the installation data. 

Regarding which users see which data, you are going to need to implement that directly into the app because the API is stateless and user agnostic, it will not hide/show data depending of the current user. 

Something like this would require code customizations to the project's core that I cannot quickly analyze here. 

If you are not sure on how to proceed, get a free quote by messaging info@easyappointments.org and have an expert take care of the integration. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
