### ISSUE TITLE
Improve date format in the backend

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1067]
Hi,

DMY, MDY and YMD are not intuitive labels. The slashes are missing and as I'm hoping for the european/german format DD.MM.YYYY soon (see #1047 and #1060), proper labeling (with dots) would be even more important.

BTW you made it right with the time format (HH:MM) -> with ":".

Cheers

**Comment by alextselegidis** [comment]
Hello! 

Right, in the future I'd like to improve the localization capabilities of Easy!Appointments so that one can configure how the app will display information. 

Price formatting is also a related topic but it does not belong to this ticket. 

Let me mark this as a future enhancement. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closing in favor of #1444

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
