### ISSUE TITLE
Uncaught TypeError: Cannot read property 'first_name' of null

### ISSUE THREAD

**Issue by etardioli** [alextselegidis/easyappointments#1070]
Hi! i've a problem with the view of the calendar, is not showing the appointments. The version of EA is 1.3.2
Any clue?
Thanks in advance!

![2021-05-11_09h38_08](https://user-images.githubusercontent.com/11684262/117819138-a07a8580-b23f-11eb-8635-e36f174ede22.png)
    at Object.<anonymous> (backend_calendar_default_view.js?52FX8:774)
    at Function.each (jquery.min.js?52FX8:2)
    at Object.success (backend_calendar_default_view.js?52FX8:770)
    at i (jquery.min.js?52FX8:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?52FX8:2)
    at A (jquery.min.js?52FX8:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?52FX8:4)

**Comment by alextselegidis** [comment]
Hello! 

The error seems to happen here: 

https://github.com/alextselegidis/easyappointments/blob/1.3.2/src/assets/js/backend_calendar_default_view.js#L774

It looks like for this appointment there is no customer assigned. 

That should normally not be the case, so it seems that you database got corrupted due to an external change (made by you or someone else). 

In any case either assign a id_users_customer value manually or change the appointment to is_unavailable = true and remove the id_services value.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
