### ISSUE TITLE
Post-installation: the following files are missing:

### ISSUE THREAD

**Issue by otheus** [alextselegidis/easyappointments#1079]
After a fresh install of v1.4.2, the following files are missing, and apparently this interferes with the login process:

* login.min.css
* general.min.css
* polyfill.min.js
* general_functions_min.js

**Comment by alextselegidis** [comment]
Hello! 

You installation does not have the minified files because you haven't executed the build steps. 

This happens if you clone from git and not download the pre-built version from the website. 

Run `npm run build` to build the files. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
