### ISSUE TITLE
request about configuration

### ISSUE THREAD

**Issue by AlessioArtini** [alextselegidis/easyappointments#1091]
Is there a way to force booking appointments in time order?
I mean:
I've 3 time slot 8:30-9:00-9:30 (for example)
I can book only in this order: 8:30 then 9:00 then 9:30
I cannot book 9:30 if It hasn't been booked before 9:00 ad 8:30
In this way There isn't "holes" in calendar.

**Comment by alextselegidis** [comment]
Hello! 

You will need to change the Availability.php library so that it only returns the first available option of the array that contains all the available hours. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
