### ISSUE TITLE
Cannot use date-picker on mobile device

### ISSUE THREAD

**Issue by ulat** [alextselegidis/easyappointments#1100]
If I want to set an appointment from the backend on my mobile device (Android as well as iOS) I cannot use the date/time pop-up window, so it's very hard to set new appointments.

**Comment by alextselegidis** [comment]
Hello! 

This problem is fixed with 1.4.2 (currently on Beta). 

It would be great if you could make a test installation and let us know if your issue still persists. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Version 1.4.2 is released, please update your installation. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
