### ISSUE TITLE
Configure number of working days per week

### ISSUE THREAD

**Issue by karltestano** [alextselegidis/easyappointments#1104]
First of all: Thanks for this great work!

In the past i have been using fullcalendar (https://fullcalendar.io/), which seemed to be part of your project.
Is it possible, to place an option field for example in the menu "enterprise logic", which configures the
duration of the week like in fullcalendar? (Please see https://fullcalendar.io/docs/timegrid-view)

For me it would be enough, to get a hint, were to set it, but i think, an option which will be configurable
would be the better solution.

Thanks in advance!
--
Greets
KarlT

**Comment by alextselegidis** [comment]
Hello @karltestano, 

Thanks for posting and for your using Easy!Appointments. 

I'm glad that you like to the project. 

FullCalendar will be updated in the upcoming release, so that more options and views become available, including the timegrid view. 

Now FullCalendar has drastically change in the versions 4 and 5 which means that lots will have to change on how Easy!Appointments handles the library but at the end the user experience will be awesome. 

The next release is scheduled for the beginnings of October. 

Stay tuned for future updates!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
