### ISSUE TITLE
Service duration values shorter than 5 minutes should be acceptable via the services page.

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1110]
Hi,

while https://github.com/alextselegidis/easyappointments/issues/1068 is solved, I cannot set service durations < 5 in backend, see screenshot. There is a error message on save with no text inside.

Setting in /application/config/constants.php -> define('EVENT_MINIMUM_DURATION', 4);

![ea](https://user-images.githubusercontent.com/51790093/130412143-a85303b8-4c39-4fdf-8c47-72e8651f0c81.png)

**Comment by alextselegidis** [comment]
Hello @h-e-l-l-o-w-o-r-l-d, 

Yes, right now and due to performance reasons the minimum service duration is 5 minutes. 

You can easily change that by changing the value of the corresponding variable in the constants.php file: 

https://github.com/alextselegidis/easyappointments/blob/master/application/config/constants.php#L90

Hope that helps!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
I'm sorry but like written in the description the value in constants.php is already set to 4 but value 4 is not accepted when creating a new service in the backend.
