### ISSUE TITLE
Security Vulnerability in https://demo.easyappointments.org/index.php/user/login

### ISSUE THREAD

**Issue by DEV696** [alextselegidis/easyappointments#1141]
I have identified a security vulnerability. Kindly let us know if we can discuss this in detail to make the product secure. Cheers!

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reaching out, please reach out to info@easyappointments.org with more details so that we can address any issues asap. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</smal<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
