### ISSUE TITLE
Feature Request: add multiple booking selection in frontend/backend

### ISSUE THREAD

**Issue by blastg** [alextselegidis/easyappointments#1165]
For recurring booking date should be very useful to add multiple appointments in the same session. This option to prevent multiple user data input like "name, surname, phone, email"

**Comment by alextselegidis** [comment]
Hello! 

Can you please elaborate on this a little bit? 

I'm not sure I completely understand what you describe. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by blastg** [comment]
Yes sorry for incomplete description. For multiple appointment I mean recurring booking (i.e. all monday at 8.00am for 1 month) or single calendar picking in the same session.
See [attached image](<a href="https://ibb.co/NYFPK8w"><img src="https://i.ibb.co/ysN1qwL/add-another.png" alt="add-another" border="0"></a>)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the clarifications. 

Recurrence is something that will be added in the app but due to its complexity it has to be planned very carefully so that it works great on all use cases. 

For this I will close this for now and create a new feature ticket when the time comes to add recurrence to the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
