### ISSUE TITLE
Error with "Timezone" to "Sao_Paulo" 

### ISSUE THREAD

**Issue by gugoan** [alextselegidis/easyappointments#1168]
Hello, I'm using easyappointments-1.4.0 and a situation is happening: When I set the "Timezone" to "Sao_Paulo" (-3:00) it allows recording several records on the same day and time (it should be only 1 in each slot of time).
When I put it as "UTC" it restricts it just right to 1 schedule per time, but it has the wrong time.

**Comment by alextselegidis** [comment]
Hello! 

First of I would advise you to upgrade to v1.4.2 as there were some availability generation fixes in the meanwhile that you may not have in your installation. 

In general it is important to grasp how timezones work in the booking page. 

All the available slots are initially generated in the provider's timezone but then converted into the customer selected timezone. 

This means that if your provider is in Sao Paolo and they're free from 9am to 10pm, a customer that checks the slots in UTC they will see your provider available between 6am and 7am.

The slots should be the same nevertheless except if the timezone difference is longer than a day. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by gugoan** [comment]
Right,
how do I work with everything in the Sao_Paulo time zone? Without the system allowing to record the same time in the same slot

**Comment by alextselegidis** [comment]
You will need to disable all the timezones from inside the `application/libraries/Timezone.php` and only keep Sao Paolo. 

At the same time make sure that the default value of the `timezone` field of the `ea_users` table is set to `America/Sao_Paulo` instead of `UTC``
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Marking this as resolved

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
