### ISSUE TITLE
Google Calendar synchronisation failure when symbols/emoji appear in events to be imported

### ISSUE THREAD

**Issue by jmadiot** [alextselegidis/easyappointments#1182]
Hello!

When I synchronise with Google Calendar, I get a failure if one of the events that is being imported contains a symbol such as "🎊" or "𝅗𝅥 " or any emoji tested for now.

The error displayed:

```
Error Number: 1366

Incorrect string value: '\xF0\x9F\x8E\x8A ' for column 'notes' at row 1

INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `is_unavailable`, `location`, `notes`, `id_users_provider`, `id_google_calendar`, `id_users_customer`, `id_services`, `book_datetime`, `hash`) VALUES ('2022-01-05 01:00:00', '2022-01-06 01:00:00', 1, NULL, 'test 🎊 ', '4', 'here is my id_google_calendar', NULL, NULL, '2022-01-04 21:27:25', 'here is a hash')

Filename: models/Appointments_model.php

Line Number: 159
```

MySQL version: 8.0.27-0ubuntu0.20.04.1.
PHP 7.4.3
Server version: Apache/2.4.41 (Ubuntu)

**Comment by alextselegidis** [comment]
Hi @jmadiot, 

Thanks for reporting this, I've seen such issues in the past and they are rare they have to be fixed. 

For now all you need to do is to change the notes column collation to `utf8mb4_general_ci` so that it can support the characters that are throwing this error. 

I will make sure this is part of 1.5 too. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by jmadiot** [comment]
Thank you @alextselegidis for providing such a quick fix!  However I'm not sure where it is supposed to take place? I changed the collation by altering the mysql table as follows but I still get the error.

```mysql
ALTER TABLE `ea_appointments` CHANGE `notes` `notes` text COLLATE 'utf8mb4_general_ci' NULL AFTER `location`;
```

(I also tried to change `$db['default']['dbcollat']` in `application/config/database.php` to no avail but that was just a random guess.)

**Comment by alextselegidis** [comment]
Hi! That should have fixed the issue but since it's still there, I'd advice you to change the collation of the entire DB/tables/columns just to make sure nothing was skipped. Since there's no single query for a change like this, I'd advice the use of a DB management app like phpMyAdmin, MySQL workbench etc. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Update: I've set the default charset and collation to utf8mb4_general_ci for the 1.5 release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
