### ISSUE TITLE
Providers and secretaries must only be able to see and manage their own customers. 

### ISSUE THREAD

**Issue by ugintl** [alextselegidis/easyappointments#1199]
Currently, the provider can see all customers. He is supposed to only see his own customers. Is it a bug or on purpose?

**Comment by alextselegidis** [comment]
Hello! 

Originally this was meant by design, but I also think that it makes more sense for providers to only see their own data. 

Marking this for 1.5

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by dj0c0ol** [comment]
I think this feature should be made with a option to disble it

**Comment by alextselegidis** [comment]
Pushed in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
