### ISSUE TITLE
booking_cancellation not working

### ISSUE THREAD

**Issue by Khaled-Proof** [alextselegidis/easyappointments#1200]
Hi, 
I successfully installed the 1.5-dev.1. And while I am trying the new release I noticed that the booking_cancellation is not working. when I open the link of my  appointment the provider is not defined somehow.
![cancel-1](https://user-images.githubusercontent.com/25641137/153034073-4324eb29-f581-4a17-9320-a30286eca961.png)

and I am having these Errors in the log file:

ERROR - 2022-02-08 17:26:57 --> The requested setting value was not found: 6
ERROR - 2022-02-08 17:26:57 --> #0  /var/www/---/---/--/application/libraries/Notifications.php(112): Providers_model->get_setting()
#1 /var/www/---/---/application/controllers/Booking.php(525): Notifications->notify_appointment_saved()
#2 /var/www/---/---/--/system/core/CodeIgniter.php(481): Booking->register()
#3  /var/www/---/---/--/index.php(341): require_once('/var/www/--...')
#4 {main}
![cancel-2](https://user-images.githubusercontent.com/25641137/153033746-d1788e70-5b67-453e-8ce4-2662139acccc.png)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing this! It'll be fixed with the next dev package. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
