### ISSUE TITLE
Datepicker in Backend's Calendar Header does not change accordinly to language and first day

### ISSUE THREAD

**Issue by albertsalles4** [alextselegidis/easyappointments#1201]
Even if the language is changed or first day of the week is marked as another day., the datepicker shown in calendar's header in the backend section does not change. I personally solved this issue by adding the parameters on the `createHeader` function in `calendar_table_view.js` file. I can submit a PR with the solution, otherwise feel free to do it yourself. :+1:

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this issue. 

The datepicker is about to change for 1.5 with a more user friendly widget, so that's a good chance to fix this issue as well. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by albertsalles4** [comment]
Great, if you need any help just let me know!
