### ISSUE TITLE
Support appointment for several days

### ISSUE THREAD

**Issue by polargeex** [alextselegidis/easyappointments#1219]
If you want book an apointment for 2 days there is no possibility in calendar 

To test this I create a services with 840 minutes (2x7 hours).

**Comment by alextselegidis** [comment]
Hello! 

That's right because Easy!Appointments will try to find an empty slot within the same day and not consequent days. 

The reason behind this is also the way availability is being configured, the working plans etc. 

Changing that requires code adjustments that cannot be easily described within a post. 

For that you may contact info@easyappointments.org and order your customization package. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
