### ISSUE TITLE
Add language settings for user

### ISSUE THREAD

**Issue by polargeex** [alextselegidis/easyappointments#1220]
To provide services in different speaking language, one user can have more than one language.

**Comment by alextselegidis** [comment]
Hello! 

There is already a new change introduced for 1.5 that includes a new field for language selection: 

https://github.com/alextselegidis/easyappointments/issues/1263

Currently the language system serves for pre-selecting the user language upon login or for communication. 

We could add multiple languages, but that would mostly serve for displaying that to the customers or other users of the app, as it would not make any functional difference at this point. 

A use case that could be used for this would be the user to select their preferred language for their booking and only get providers that speak this language as an option but this is currently out of the scope of the app. 

So instead I propose that you add the supported languages to the service descriptions so that customers know which languages are available in a business or create language based services. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
