### ISSUE TITLE
Find the first available provider on hour selection

### ISSUE THREAD

**Issue by mariosmaniatis** [alextselegidis/easyappointments#123]
Hello is any possible way to find which provider is available(if you choose any-provider on provider selection(first tab)) before you book the appointment? I created a field under available hours(second tab) and i want to fill it with first's provider name. 
Something like: i choose 28/3/2016 , 20:30 time.
On tab number 4 there is the selected provider: (any-provider in my case)(blue letters).
I want to show the first provider available and not "any-provider".
Thanks for your time.

**Comment by alextselegidis** [comment]
The app will always fetch the provider that has the most free time on his plan. You can modify the "ajax_get_available_hours" method in the appointments.php controller to return the providers data (since the provider ID is given by the "search_any_provider" method) along with the available hours. 

I will not add you request as a new feature because there will be a new setting in the future which will disable this "any provider" entry, in case someone does not need it.
