### ISSUE TITLE
[1.43] Time of appointment in email is UTC

### ISSUE THREAD

**Issue by mamisoa** [alextselegidis/easyappointments#1234]
Hi, we have some problems with patients taking the right appointment at the right time but coming at the time of the email which is set UTC. This was not the case with version 1.41. Is it possible to modify this setting ? ![image](https://user-images.githubusercontent.com/8473545/163940802-a38831b5-e396-4c0e-bf72-c09746623988.jpeg)

**Comment by alextselegidis** [comment]
Hello! 

The time zone originates from the customer selected time zone value during the booking and the provider time zone value. 

Did you change those to match the actual ones? 

Also please make sure you update to 1.4.3 in order to get the latest improvements and fixes. 

If you are not sure on how to proceed, reach out to info@easyappointments.org and book the Upgrade Service. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mamisoa** [comment]
Thanks for the answer. 

Actually, I did the upgrade from 1.4.1 to 1.4.3 to get this behaviour.

So this is happening under 1.4.3, which was not the case with previous version. Patients are mostly in the same timezone (Brussels +1.00 or CEST), and the appointment is at the right time (cf ICS file), but the email is confusing as it shows the time in UTC.

**Comment by mamisoa** [comment]
Sorry for the trouble. The account of the secretary that receive the notification was set as "UTC". My fault.

Thanks a lot for your help and magnificent work.
