### ISSUE TITLE
Use the default service duration for new appointments, if the user just clicks on a single slot in the backend calendar

### ISSUE THREAD

**Issue by aparrot89** [alextselegidis/easyappointments#1237]
When I want to make an appointment directly on the calendar (as a secretary for example) the appointment time is not right. It is 15 minutes long (by default), whereas the service proposed lasts 10 minutes.

<img src="https://i.ibb.co/VCpbpHr/Screenshot-2022-04-21-at-15-38-24.png" alt="Screenshot-2022-04-21-at-15-38-24" border="0">

<img src="https://i.ibb.co/1X8xqsv/Screenshot-2022-04-21-at-15-38-36.png" alt="Screenshot-2022-04-21-at-15-38-36" border="0">

I have to change service and then come back to this one and there it is 10 minutes.

<img src="https://i.ibb.co/c88gsvX/Screenshot-2022-04-21-at-15-38-45.png" alt="Screenshot-2022-04-21-at-15-38-45" border="0">

<img src="https://i.ibb.co/Sn8ThGV/Screenshot-2022-04-21-at-15-38-53.png" alt="Screenshot-2022-04-21-at-15-38-53" border="0">

**Comment by dogukansahil** [comment]
I have that same problem. If you select the add appointment option above, this will not be a problem.

**Comment by aparrot89** [comment]
Yes.
A small bug that can surprise the user.

**Comment by alextselegidis** [comment]
Hello! 

This will only happen if you select the slot directly from the calendar. 

The user is able to select an arbitrary time for the appointment and the app will apply the start and end time accordingly. 

Now I think an improvement to this would be to use the default service duration instead of the 15 minute slot if there is no drag selection in the calendar. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Pushed in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Pushed in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
