### ISSUE TITLE
[1.5] User UI language not restored from session

### ISSUE THREAD

**Issue by JanC** [alextselegidis/easyappointments#1249]
hey,
when I change the UI language then  log out and login again, the UI is in English again. It seems this setting is stored under the ea_session `;language|s:6:"french"; ` but not restored when logging back because the entire session file is deleted.

In the `master` the session file remains even after user logout. 

Would it make sense the store the user language setting in the database? There is already a language field in the user table

**Comment by alextselegidis** [comment]
Hi @JanC, 

That's because 1.5 will destroy the entire session instead of some properties, which is more appropriate in the long term. 

Even if the language would still be available from the previous session, it would expire after 2 hours (session TTL), so the best solution would actually display a new setting and allow the user to select the default language. 

I'll close this ticket and create a new one for this change. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
