### ISSUE TITLE
Error After Having Upgraded To Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by guillaumesoucy94** [alextselegidis/easyappointments#1259]
Hello, 

After upgrading to Ubuntu 22.04 LTS, I do encounter that error when accessing the site, I pasted the content here:

http://pastebin.zsites.ca/view/e878c90a

What is wrong and how to fix it. 

If I revert the VM backup back to Ubuntu 20.04 LTS, the site load correctly without any errors.

Best regards, 

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello, 

Is someone can please help me?

Thank-you

Guillaume

**Comment by alextselegidis** [comment]
Hello! 

It looks like that during the server upgrade the PHP interpreter was removed or got deactivated, because the server is not executing PHP code any more. 

Instead and since PHP is inactive on your server, it serves PHP files as if they are plain text or HTML files, which is also the reason you are getting their contents. 

Make sure you re-enable PHP execution again and the problem will go away. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by guillaumesoucy94** [comment]
Hello, 

Ok, I will try and post the updates here. 

Thanks!

Guillaume

**Comment by guillaumesoucy94** [comment]
It works! Thank-you!
