### ISSUE TITLE
How to allow only registered customers to book an appointment

### ISSUE THREAD

**Issue by openSourcerer9000** [alextselegidis/easyappointments#1270]
There's a backend section for adding and managing customers, yet it seems anyone can go in and book an appointment, creating a new customer in the database. 

How do I set it to only allow customers pre-registered as customers to book an appointment? 

Thanks

**Comment by hesco** [comment]
I too would find this helpful.

**Comment by alextselegidis** [comment]
Hello! 

In one of the future versions I will add the support for guest and registered customers, so that users can select the type of users that are allowed to make new appointments. 

I will therefore close this ticket for now. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
