### ISSUE TITLE
how to add customers in rest api

### ISSUE THREAD

**Issue by harikishna** [alextselegidis/easyappointments#1303]
i am getting an internal server error

form.addEventListener('submit', function(e) {
    let firstName = document.getElementById('fullname').value;

const email = document.getElementById('email').value;
const phonenumber = document.getElementById('phonenumber').value;
const data={
   
    firstName: fullname,
    lastName:"lastname",
    email: email,
    phone:phonenumber
  }

console.log(data)
    // Prevent default behavior:
    e.preventDefault();
    fetch('https://appoinments2.mauvetix.com/index.php/api/v1/customers', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer admin',
    
  },
  body: JSON.stringify(data)
  
})
  .then(response => {
    console.log(response)
  })
  .catch(err => {
    console.log(err)
  })
})

result  
POST https://appoinments2.mauvetix.com/index.php/api/v1/customers net::ERR_ABORTED 500

**Comment by alextselegidis** [comment]
Hello! 

Please check what the error is and post it here so that we can troubleshoot: 

https://easyappointments.org/2021/05/31/how-to-troubleshoot-easyappointments/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
