### ISSUE TITLE
Questions about dev branch

### ISSUE THREAD

**Issue by ugintl** [alextselegidis/easyappointments#1304]
1. When is Ver 1.5 expected?

2. What version of nodejs i should use?

3. What is the purpose of command `npm run build`?

4. Is this how i will download the dev or develop branch? `git clone --branch dev --single-branch https://github.com/alextselegidis/easyappointments.git`

**Comment by ugintl** [comment]
Above command is incorrect. This command worked `git clone --branch develop --single-branch https://github.com/alextselegidis/easyappointments.git`

I am using nodejs 16 and saw following warnings while running npm install

```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
```

**Comment by alextselegidis** [comment]
Hello! 

1. It's almost done, so any time soon 
2. Use the current LTS
3. It will build all the asset files and perform the required tasks so that you can the production ready zip archive of the app you can install on your server. 
4. If you want to develop yes, otherwise I would suggest you use one of the pre-built packages posted on the official websites. 

The warnings you get in nodejs are from packages that require some updates but those updates are not there yet. Since we are not using the Node Modules at all in production you can safely ignore them or even try to update the packages yourself (only if you have cloned from Github)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
