### ISSUE TITLE
Feature Request: /index.php?service=n should serve a single service; /index.php?service=0 should provide the service selector

### ISSUE THREAD

**Issue by hesco** [alextselegidis/easyappointments#1313]
/index.php?service=n should serve a single service; 

/index.php?service=0 should provide the selector allowing the user to choose a specific service.  

It should be possible to link to / expose an appointment setting tool for a single service without confusing a prospect about other services offered by a service provider.

**Comment by hesco** [comment]
This selector seems to get built in this view:
```
./application/views/appointments/book.php
```
but I do not see anything assigning the SELECTED attribute to the options.  I suppose that is happening in the javascript, somehow.  Also, I am seeing plenty of references to service_id in the code, but have been unable to sort out how the service argument is being parsed from the url.  

I'm guessing that perhaps the ?service= value may somehow be assigned to the $service['service_id'] somewhere, but have not yet confirmed that.  The new behavior I am recommending would be a function of that value.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

I'm not sure I quite grasp your proposal... 

Could you please elaborate?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by hesco** [comment]
`/index.php` exposes a selector giving the user the option of choosing a specific service.  Appending `?service=n` allows you to pre-select as a default, the service you wish to feature.  Sometimes I want my users to have that option.  Sometimes I want to focus a user on the widgets I'm selling, rather than to distract them by providing them the option to look at the fidgets I might also sell.  I tried to grab a screen shot, but was unable to keep the selector open when I invoked the screen shot tool.  

I propose that `/index.php?service=n` should offer the user NO options, only the chosen service.  Perhaps `index.php?service=0` might offer no SELECTED default but the entire set of options.  Does that clarify?

**Comment by alextselegidis** [comment]
Hello!

Thanks for getting back with more information. 

So you are saying that we should not allow the user to change the service, if they use a service-preselection-link, right? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by hesco** [comment]
Yes, though perhaps to maintain backwards compatibility it might make sense to assign this new behavior to a new query string parameter.  Perhaps the service=n parameter should provide the original behavior and a new svc=n parameter would provide this proposed new behavior.  That would surely be less disruptive to your existing user base.  And still allow people to offer the range of services while also offer a pre-SELECTED default value.

**Comment by alextselegidis** [comment]
Hello! 

Right now E!A would skip the first step if both service and provider are preselected, with their own booking link (coming with 1.5). Although that requires the pre-selection of a provider, that should cover most basic cases for now. 

The problem with the proposal of this ticket is that some users would like the customer to be able to change and some will not. For that it makes more sense to create a new component that will generate those links exactly the way you want them to, but this is something that will come in a future release. 

In order to make this work as needed, you will need to modify frontend_book.js as shown below

<img width="967" alt="Screenshot 2022-11-02 at 15 21 49" src="https://user-images.githubusercontent.com/4527441/199500392-1489bf1a-cd5e-4a8d-a685-8abfd23c9abf.png">

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
