### ISSUE TITLE
Problem with Working Plan of 1 hour

### ISSUE THREAD

**Issue by rokka** [alextselegidis/easyappointments#1317]
I am using EasyAppointments 1.4.3 with this Docker image => https://hub.docker.com/r/jamrizzi/easyappointments

```
docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=hellodocker -e MYSQL_DATABASE=easyappointments mariadb:latest
docker run --name some-easyappointments -e BASE_URL=https://termin.heyneuer.com -e LANGUAGE=german -e TZ=Europe/Berlin -d --link some-mariadb:db -p 8888:8888 jamrizzi/easyappointments:latest
```

I have set up one provider like so:

![image](https://user-images.githubusercontent.com/533290/198867985-cac1d234-42a9-4621-9dfd-f1d6783e7919.png)

As soon as I book the first appointment I get the following error when trying to add a second appointment

```
AJAX Error: 
Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /app/www/application/controllers/Appointments.php on line 1043
Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /app/www/system/core/Exceptions.php on line 1
```

If I remove the exsting appointment the error will disapear until I book one appointment again.

This is the current content of the Database: [easyappointments.txt](https://github.com/alextselegidis/easyappointments/files/9895364/easyappointments.txt)

Any help is very appreciated
Andre

**Comment by alextselegidis** [comment]
Hello! 

If you solved this issue, could you please provide the solution so that other users can benefit form that? 

Thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rokka** [comment]
Hi,

excuse me. I have just updated to the latest version (1.4.3) and the problem didn´t happen again.

The latest version forced a minimum duration for a service to be 5 minutes.

In the earlier version I have chosen 3 minutes. Maybe this was part of the problm.


Greetings
Andre
