### ISSUE TITLE
Admin credentials stopped working. How to reset?

### ISSUE THREAD

**Issue by arladmin** [alextselegidis/easyappointments#1336]
My admin credentials have stopped working, for some unknown reason. 

How do i reset them from the OS? (Forgot Password page is not accepting the username and email)

**Comment by alextselegidis** [comment]
Hello! 

In this case you need to edit your user's DB entry, in the `ea_user_settings` table and set the following values: 

* password = 784084a8a6b90f24f0680b204fef2a2d25ed4302e94f3a9c76623bf8205f7897
* salt = b4cc4f3bd171a5fe15d6217d44c320512afa7f72ffa7d8a9e7f2e75a842e7abc

Those two correspond to the password "administrator". 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by paquitto99** [comment]
ok, on this line, my problem to be in the next step.

my password is correctly but, dont go to backend... all time stay in login page. I try write /backend in the url, but return to de login page, and the password is ok because dont show message label red of incorrect password...

**Comment by alextselegidis** [comment]
I think the issue is that your storage folder is not writable by the PHP process and thus no session files can be created. 

Please make the "storage" folder writable (change permissions or owner recursively)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
