### ISSUE TITLE
Overrides

### ISSUE THREAD

**Issue by patrickus33** [alextselegidis/easyappointments#1338]
It would be nice to be able to override the file rather than modify the original file.

In case of updates, the changes would not be erased.

Also, it would be nice to be able to create a "custom.css" in which you could modify the native css rules without this file being deleted in case of an update.

**Comment by alextselegidis** [comment]
Hello! 

If you create a root directory called custom and allow place all your custom files in there, you will then be able to keep them in place after each release. 

In the near future, an E!A package API will become available so that you can prepare sharable packages for the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
