### ISSUE TITLE
Removing a customer record from the customers page must not result in an error. 

### ISSUE THREAD

**Issue by skerbis** [alextselegidis/easyappointments#1345]
When I delete a customer in the system, the associated appointments are not deleted or adjusted. This leads to an error with Missing ClientID. 

A quick fix could be a foreign key in the database. However, the appointments are then gone, which may not be in the employee's best interest.

**Comment by alextselegidis** [comment]
Hello! 

Did you try to delete a customer from within the app, from the API or manually from the database? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
I've deleted the customer within the app.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for getting back on this. 

In general there is a foreign key in the database but with v1.5 I've introduce soft-deletes in the app. 

The reason is that removing the customer must not remove their past appointments as if they never happened. 

That must normally be an option for the user to decide. 

The error can quickly be fixed by using the `$with_trashed` argument while getting the appointment resources from the appointments model class. 

But I'll still have to fine tune the soft deleting functionality for a better user experience. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

I checked this again with the latest `develop` code state and what happens is that all the customer appointments are also automatically removed from the calendar, so that you cannot see them.

This resembles the original foreign key based logic while keeping the data in the database just in case they are needed. 

Could you try with the develop instance? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
Sorry. We decided to use a different solution. (I love yours, but customer decided)  Sorry for late answer. Can't test now.
