### ISSUE TITLE
1.5.0-dev.4: Error "Unknown column 'delete_datetime' in 'where clause'" after updating from 1.4

### ISSUE THREAD

**Issue by pixi** [alextselegidis/easyappointments#1378]
This 
![2023-07-04 at 12 03 38](https://github.com/alextselegidis/easyappointments/assets/7418913/96778b5b-f547-4afa-a7db-3128597b9d0d)
appeared:
1) after I replaced all data from 1.4 with the new content and 
2) called "http://url-to-ea-installation/index.php/backend/update" and
3) added my working credentials (tested with previous version)
PHP is 8.1

Any idea what's wrong?

**Comment by alextselegidis** [comment]
Hello! 

It looks like there is a table that was not migrated correctly. 

This could be due to the migration logic. 

Where do you get this error? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by pixi** [comment]
As described above I just replaced the v1.4 version with the data from v1.5 and called the url.
Afai understood the migration is done by the "backend/update", right?

Is there a way to track when and how/where it happens.

**Comment by alextselegidis** [comment]
Hello! 

> Afai understood the migration is done by the "backend/update", right?

This route is changed for 1.5, you will need to open "/update" or run "php index.php console migrate" in the terminal. 

> Is there a way to track when and how/where it happens.

You can check the latest migration run by opening the "migrations" table. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
