### ISSUE TITLE
Non-working time not showing correctly in the week view of calendar

### ISSUE THREAD

**Issue by venks** [alextselegidis/easyappointments#1381]
My timezone is Australia/Melbourne (GMT+10) and I've seen that the non-working time is not shown correctly in the  week view of calendar.

For eg,

![image (3)](https://github.com/alextselegidis/easyappointments/assets/824345/c3a70d35-ecba-4b17-8822-604958f98081)

are the working times set but non-working times are displayed as below:

![image (2)](https://github.com/alextselegidis/easyappointments/assets/824345/954329b0-a3d0-44a2-b8af-a95e73a0e95a)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

It will be fixed before the next release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hi @venks, 

I see that this used to be an issue with the E!A v1.4.3 but the current upcoming 1.5 is already using a newer version of the Calendar and a different way to parse dates. 

Could you please give a test with the latest 1.5 dev package, and let me know if this is still a problem? 

https://github.com/alextselegidis/easyappointments/releases/download/1.5.0-dev.4/easyappointments-1.5.0-dev.4.zip

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by venks** [comment]
Hi @alextselegidis we actually forked at v.1.4.3 and have a few changes that would be overwritten with v1.5.0
Are you able to point us at all to where these changes might be so we can go in and cherry pick?

**Comment by alextselegidis** [comment]
Hello @venks, 

Unfortunately that is impossible, because there are many things that are different (including the MVC structure). It will probably be easier to move your custom changes to the new release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Update: this issue is resolved on develop and will be part of the next 1.5 package

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
