### ISSUE TITLE
Feedback to 1.5.0-dev.4

### ISSUE THREAD

**Issue by helmutkaufmann** [alextselegidis/easyappointments#1401]
Thanks Alex, for the great work. I have downloaded version 1.5.0-dev.4 . Here some feedback:
- In *config.php*,  GOOGLE_PRODUCT_NAME and GOOGLE_API_KEY are not defined and therefore the installation did not work.
- The provider is receiving two confirmation mails, one with the chosen timezone and one with UTC
- While email worked in 1.4.3, I had to add SMTP information to *application/config/email.php* - I assume this should also go into the *config.php* but *application/config/email.php*  seems not set up to deal with constants defined in *config.php*.
- If I enter a company email address, this address is also used as the sender address in the emails. It would be great if it were possible to add the full company name to the address field, so it is clear where the mail is coming from.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the feedback! 

> In config.php, GOOGLE_PRODUCT_NAME and GOOGLE_API_KEY are not defined and therefore the installation did not work.

Those are not needed nor used in teh code, so the problem you are getting is probably in a different place and due to a different reason. 

> The provider is receiving two confirmation mails, one with the chosen timezone and one with UTC

This can only be the case if you use the same email as a customer and as a provider. By default providers are on UTC unless you change their timezone from the users page while creating them 

> While email worked in 1.4.3, I had to add SMTP information to application/config/email.php - I assume this should also go into the config.php but application/config/email.php seems not set up to deal with constants defined in config.php.

Could you please post the error here for further troubleshooting? 

> If I enter a company email address, this address is also used as the sender address in the emails. It would be great if it were possible to add the full company name to the address field, so it is clear where the mail is coming from.

I agree, in general the from address must also be part of the email configuration, so I will try to change that before the stable release

**Comment by alextselegidis** [comment]
Quick update on this one: 

It is now possible to configure the from-address/name and the reply too as well, so this ticket can now be resolved

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
