### ISSUE TITLE
Problem with Brazilian Portuguese translation

### ISSUE THREAD

**Issue by SrMarkLau** [alextselegidis/easyappointments#1439]
Hello everyone, when using the application with the 'portuguese-br' language configuration in the config.php file, the application also shows external users the page in Portuguese for Portugal and not for Brazil. Is there another type of configuration to be done?

**Comment by SrMarkLau** [comment]
I think it's a bug in the application/config/config.php file on line 118:

$config['language'] = isset($_SERVER['HTTP_ACCEPT_LANGUAGE'], $languages[$language_code])
 ? $languages[$language_code]
 : Config::LANGUAGE;

**Comment by alextselegidis** [comment]
Hello! 

This happens because of the browser configuration most likely. 

The app will automatically try to detect the browser language. 

You can skip that by updating config.php to work like this: 

$config['language'] = Config::LANGUAGE;

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
