### ISSUE TITLE
Appointment modal start/end time initially set to slotDuration rather than service duration

### ISSUE THREAD

**Issue by mynameisjonas** [alextselegidis/easyappointments#1449]
Hi Alex, 

Our providers often book appointments over the phone or in person and therefore use the backend to create a new appointment. 

They do this by clicking on the calendar time slot that brings up the backend appointment modal window. 

Something we have noticed is that when form loads the Start Date/Time and End Date/Time defaults to the slotDuration of the calendar which in our deployment we have set to 30min. This happens even if the Service and Provider have "default" values (the provider being populated with a value provided the calendar view is not set to "All")

Most services are longer that this and the most common service duration is 45mins. 

The provider needs remember to change the Service to something else then change it back again in order to get the correct duration before saving the form otherwise the appointment will be booked with the incorrect duration.

I've tested this behaviour with 1.5.0 dev 4. 

One workaround would be to clear the Service option value when the form is initialised so that the provider always needs to select something.  Is that a relatively easy code change? 

Many thanks for all your hard work on this project!

mynameisjonas

**Comment by mynameisjonas** [comment]
An example here from the public demo @ 1.4.3.  Clicking on the calendar slot (where the default slot is 15mins) means the start/end duration is 15mins where the service is 30mins 

<img width="1102" alt="image" src="https://github.com/alextselegidis/easyappointments/assets/4792161/87a99aac-aee1-4cb2-9648-288a90c81409">

**Comment by alextselegidis** [comment]
Hello! 

That is correct, the calendar widget will try to set start/end values based on what was selected in the calendar. 

In some cases that makes sense as it will save the user from typing in that manually. 

In other cases (like yours) that would be a problem, cause you would not care about the calendar selection but on the selected service. 

I guess a compromise will make it so that if the user clicks and not click and drag in the calendar, the default times will be selected

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mynameisjonas** [comment]
Hi Alex,

Yes I think that would make sense - if the user single clicks a specific time slot then use the selected start time + service duration to calculate end time of the appointment. A click and drag is perhaps a more intentional action and implies the person making the booking has a specific appointment duration in mind. 

Keep up the great work and congrats on the 10 year milestone !
