### ISSUE TITLE
Working Plan for each service

### ISSUE THREAD

**Issue by FraOre** [alextselegidis/easyappointments#145]
Hi Alex and thank you so much for the great work!
Its really powerfull!

I need to change the provider Working Plan by the service. For example: I have 2 services: Visit Showroom and Test drive. Now the Provider A works on the service Visit Showroom from Monday to Saturday, but in the second service, Test drive, he doesn't work on Monday. So if I remove the Monday from his Working Plane its not possible schedulate an appointmant on Visit Showroom...

Can you help me?

**Comment by alextselegidis** [comment]
Hi there :) 

Unfortunately what you need is not available at the moment and I don't see it coming soon due to other  priorities. 

As a quick n dirty solution I would recommend you to create two providers with the same name but different emails (not good I know), each one will only serve one service and have different working plans. 

Thanks for your recommendation though :+1:
