### ISSUE TITLE
American Time Format (AM/PM)

### ISSUE THREAD

**Issue by bbruman** [alextselegidis/easyappointments#152]
This was marked settled a while back:
https://github.com/alextselegidis/easyappointments/issues/27

But only the date format was made changeable, not the time format.

Is there anyway this can be added, or does anyone know how to properly modify existing code to support AM/PM time format?

**Comment by bbruman** [comment]
I figured out how to do this manually by changing instances of `H:i` to `g:i a` in code

**Comment by alextselegidis** [comment]
Nice :)

**Comment by AurelienC** [comment]
Hello,

Is it possible to choose 12h or 24h format ?

**Comment by alextselegidis** [comment]
@AurelienC This is going to be a feature of 1.3.1 (currently under development). 

This new release will enable users to switch between the regular and military format. 

Stay tuned for project updates. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by AurelienC** [comment]
You could change it in `easyappointments/src/assets/js/frontend_book_api.js`


```
81 | '<span class="available-hour">' + Date.parse(availableHour).toString('**h:mm tt**') + '</span><br/>');
-- | --
82 | });
83 |  
84 | if (FrontendBook.manageMode) {
… |  
89 | GlobalVariables.appointmentData.start_datetime,
90 | 'yyyy-MM-dd HH:mm:ss').toString('**h:mm tt**');
91 | }).addClass('selected-hour');
```

**Comment by alextselegidis** [comment]
@ejtipi There are many places that include the time format so there is unfortunately no direct way to do this. 

The upcoming v1.3.1 will provide a setting so that users can switch between regular and military time :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
