### ISSUE TITLE
Suppress warning errors and check the environment before using ldap

### ISSUE THREAD

**Issue by tm8544** [alextselegidis/easyappointments#1540]
I think there is still a problem in [application/libraries/Ldap_client.php](https://github.com/alextselegidis/easyappointments/commit/3f39861e4a7e702cd8c66b512c039ce64fe3080b#diff-2c08bf98c2f0cf4a5250ed04045600809889199bf33a8ae51e03b8dd6eb8a9ca) after 3f39861.

I have `ldap_is_active = 0` in settings.
When I try to login to backoffice with false credentials, I get `The LDAP extension is not loaded`, but I think I should get `Invalid credentials provided, please try again`.

Should `$this->check_environment();` on line 87 be after

```
$ldap_is_active = setting('ldap_is_active');

if (!$ldap_is_active) {
    return null;
}
```
in lines 89-93?

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

All LDAP calls are now suppressed so that errors render correctly and the app works even without the plugin. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
