### ISSUE TITLE
Limit service to a specific datetime range

### ISSUE THREAD

**Issue by ml1nk** [alextselegidis/easyappointments#1570]
If some services are only available during an event (like a mess) it would be helpful to limit the availability of a service to a specific datetime range.

**Comment by alextselegidis** [comment]
Hello! 

This is possible with working plan exceptions

Create a service and a unique provider that works in no day

Then add a working plan exception for the required event time and allow users to only book this slot 

You can change the attendants number from the service 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ml1nk** [comment]
Hi.

Thanks for your reply. It's kind of a workaround, but should work on our case.

Is there a way to start the date selection in a month where something is available?

For example I only enabled some days in October, but still it starts in July.

![image](https://github.com/user-attachments/assets/a11db74d-3fa8-4eb9-a411-2d93bb9da09e)
![image](https://github.com/user-attachments/assets/5f41ddd0-4d35-4dfb-b8ce-94e3670409c5)

**Comment by alextselegidis** [comment]
Normally the app will check for the next 3 months for availability. 

This could be changed directly in code and make it looks for e.g. 6 or 9 months but that would trigger a lot of calculations on the server. 

That would probably need to be cache-stored so that it can be pulled more easily. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ml1nk** [comment]
I didn't meant to change how many months it checks the availability for, but hide months in the selection where nothing can be selected (like Juli, August and September).

**Comment by alextselegidis** [comment]
Oh I see. I'll need to check if the date picker we're using supports this, because it may otherwise become a cumbersome task to pull off. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
