### ISSUE TITLE
Login dashboard for customers.

### ISSUE THREAD

**Issue by kawish** [alextselegidis/easyappointments#17]
Please create a login dashboard for clients where they could see their previously booked appointments

Create a login panel for clients

**Comment by alextselegidis** [comment]
Will keep this as a feature request but not for v1.1. 

There are features that are more urgent to implement currently, sorry. Still customers are able to check their booked appointments through their email notifications.

**Comment by kawish** [comment]
You have done an incredible work

Will be eagerly waiting for the update

**Comment by alextselegidis** [comment]
Thank you very much :) Stay tuned!

**Comment by guitarzero** [comment]
Would be a cool feature. Thanx for your great work

**Comment by ahukkanen** [comment]
+1

**Comment by PowerChaos** [comment]
+1

**Comment by indiscripts** [comment]
+1

**Comment by spgianna** [comment]
+1

**Comment by alextselegidis** [comment]
Hello everyone, I know it's been a while than this request was posted here but I'm marking this as a feature for version 1.5 🎉 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by JHHMobile** [comment]
do you have a timeframe for V1.5.0? Thanks

**Comment by liemteksun** [comment]
+1

**Comment by alextselegidis** [comment]
Quick update on this one ... 

There are some major changes coming that will enable better integration with more external systems (e.g. CalDAV), and while I'm researching and preparing for such changes I see that the data structure has to slightly change till so that everything works smoothly with those services. 

For that, I will need to postpone cancel the implementation of this ticket, until the new database structure comes. 

Changing the db structure also requires additional attention so that we can make sure we do not break anything during the migrations. 

Stay tuned for future updates.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
