### ISSUE TITLE
Mistake in wiki (base url)

### ISSUE THREAD

**Issue by wuyuanyi135** [alextselegidis/easyappointments#181]
> Upload the Easy!Appointments source files to your server. You can place the files into a directory with named "easyappointments" or "appointments" or "book" etc. Make sure that you mark the Easy!Appointments folder URL because it will be needed in the following step. For example if the system files are placed in the this directory ".../httpdocs/easy_appointments/" then the URL to this folder will be *"http://your-domaThis URL will be needed in the following step.*

in https://github.com/alextselegidis/easyappointments/wiki

I can hardly understand what the last sentence mean. Can you explain how can I set this variable?

**Comment by alextselegidis** [comment]
Oh thanks for noticing :) 

So this means that E!A needs the public URL in order to work. This is actually the URL you are using to access the Easy!Appointments installation. So this paragraph states that you will need to copy this URL and added to the config.php 

Example: 

Installation Path: `/var/www/public_html/easyappointments`
Public URL: `http://your-domain.com/easyappointments` >> Use this as BASE_URL in config.php

I hope this makes it more clear to you.

**Comment by alextselegidis** [comment]
Corrected :)
