### ISSUE TITLE
Already created services, providers, users, categories not being listed in the backend

### ISSUE THREAD

**Issue by abeninskibede** [alextselegidis/easyappointments#2]
Hey guys I can't see already created ervices, providers, users, categories in the backend.

**Comment by bkrajendra** [comment]
check whether everything is getting saved or not.
Use chrome console and network tab to see whether its getting posted to proper URL.
In my case found my post URL to be something like  this 
http://drajitraut.iocare.inbackend_api/ajax_save_settings instead of 
http://drajitraut.iocare.in/backend_api/ajax_save_settings

which is due to Base URL setting. Make sure it should be 
http://example.com/
