### ISSUE TITLE
blank page after installation of 1.2 alpha version

### ISSUE THREAD

**Issue by Hassan221** [alextselegidis/easyappointments#230]
Installed alpha version and getting blank page after opening 

myurl/index.php/backend

Also not recommended in installatio guide, I uploaded structure.sql to database, but still getting blank page. Also checked phip and mysql version of my system which all are up to date.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi Hassan221,

what happens if you open yoururl/index.php (without "backend")?
Were you using the backend of easyappointments (a different version) at this url before? If yes you most probably have to delete the corresponding cookies in your browser...
Do you see anything in the error-log of your web-server?

Greetings
Hermann

**Comment by alextselegidis** [comment]
Hello everyone :) 

Would you mind enabling the debug output (root config.php) and share any possible error logs?

**Comment by alextselegidis** [comment]
I will close this issue as we do not have any feedback from the user.
