### ISSUE TITLE
Stylesheet not working using HTTPS (Apache2)

### ISSUE THREAD

**Issue by absolutejam** [alextselegidis/easyappointments#235]
Really sorry to bug you as I realise it's not directly related to Easy!Appointments.

I've served the page using Apache2, and in my config file I have the following:

```
<VirtualHost *:443>
        ServerName foo.bar.com

        ServerAdmin support@foobar.com
        DocumentRoot /var/www/easyappointments

        SSLEngine on
        SSLCertificateFile    /etc/ssl/mycert/mycert.crt
        SSLCertificateKeyFile /etc/ssl/mycert/private_key.key
        SSLCertificateChainFile /etc/ssl/mycert/gs_intermediate_ca.crt

</VirtualHost>
```

When I access the page using HTTP, it renders fine, but using HTTPS, I get the following:

![image](https://cloud.githubusercontent.com/assets/6817942/20061678/bc9f3548-a4f8-11e6-8bc6-c0d3b708c458.png)

Any ideas?

**Comment by hermannschwaerzlerUIBK** [comment]
Hi James,
what have you configured as value for ``BASE_URL`` in ``config.php``?
Does that start with "https:"?
If it's "http:": Try to remove the scheme (URL starts with "//") or if that does not work use "https:".
Greetings
Hermann

**Comment by alextselegidis** [comment]
Hermann is right, the problem lies in the BASE_URL value. If you open the browser's console you will see that the css and js files couldn't be loaded due to an invalid URL request (404 Not Found).

**Comment by absolutejam** [comment]
Thanks guys. I changed the `BASE_URL` to just begin with `//` instead of `http://` or `https://` and it works fine on both now. Thanks for your help, I've not got my site running on SSL only!

**Comment by navinisaac** [comment]
I realize this issue is closed but I figured I would put this here in case anyone comes across this in the future. When I amended the base_url to be 'scheme-less' (//), I had strange behavior with the booking success notification; it would not send the email to the customer or the provider. Logs (image below) showed the following. After changing the base_url to https:// it seemed to resume working properly.

Thanks Hermann and thank you Alex! Very nice piece of software!

![image](https://cloud.githubusercontent.com/assets/25622779/24784565/7f8c1082-1b21-11e7-98e0-67272dd8d798.png)
