### ISSUE TITLE
Base URL and Rewrite in htaccess

### ISSUE THREAD

**Issue by jirijanata** [alextselegidis/easyappointments#246]
Hello,

first of all, thank you for awesome application. I would like to ask about one problem. The Biggest webhosting provider in Czech Republic is using .htaccess for creating subdomains and aliases in their webhosting - so I can use more domains in one webhosting. In root of webhosting is this .htaccess:

```# htaccess rules for subdomains and aliases
# to create new subdomain, create a folder www/subdom/(subdomain name)
# to create web for alias, create a folder www/domains/(whole domain name)

# htaccess pravidla pro subdomeny a samostatne weby aliasu
# pro vytvoreni subdomeny vytvorte adresar www/subdom/(nazev subdomeny)
# pro vytvoreni webu pro alias vytvorte adresar www/domains/(cely domenovy nazev)
# dalsi info a priklady: http://kb.wedos.com/r/32/webhosting-htaccess.html

RewriteEngine On

# cele domeny (aliasy)
RewriteCond %{REQUEST_URI} !^domains/
RewriteCond %{REQUEST_URI} !^/domains/
RewriteCond %{HTTP_HOST} ^(www\.)?(.*)$
RewriteCond %{DOCUMENT_ROOT}/domains/%2 -d
RewriteRule (.*) domains/%2/$1 [DPI]

# subdomeny (s nebo bez www na zacatku)
RewriteCond %{REQUEST_URI} !^subdom/
RewriteCond %{REQUEST_URI} !^/subdom/
RewriteCond %{HTTP_HOST} ^(www\.)?(.*)\.([^\.]*)\.([^\.]*)$
RewriteCond %{DOCUMENT_ROOT}/subdom/%2 -d
RewriteRule (.*) subdom/%2/$1 [DPI]

# aliasy - spravne presmerovani pri chybejicim /
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^domains/[^/]+/(.+[^/])$ /$1/ [R]

# subdomeny - spravne presmerovani pri chybejicim /
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^subdom/[^/]+/(.+[^/])$ /$1/ [R]
```

I have Easy Appointments in folder www/domains/ea.domain.com.

If I configure  const BASE_URL in config.php to http://ea.domain.com/domains/ea.domain.com, everything works fine, but url looks bad - like http://ea.domain.com/domains/ea.domain.com/index.php/user/login

Can you give me an advice, how to use just "simple" base url like http://ea.domain.com?

Thank you very much

EDIT1:
I found, that you are using CodeIntegrer in your application. I also found, that there should be possible to change this two parameters and edit .htaccess - but it does not work for me..

https://webtrh.cz/278763-wedos
application/config/config.php
row 41
`$config['index_page'] = 'index.php';`
`$config['index_page'] = 'index.php?';`

row 59
`$config['uri_protocol']	= 'AUTO';`
`$config['uri_protocol']    = 'QUERY_STRING';`

add to .htaccess
```RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?$1 [L]

**Comment by alextselegidis** [comment]
Normally setting the BASE_URL to "http://ea.domain.com" should work because the redirection is happening internally in the server.

Other users solved their problems by doing this and therefore I created a FAQ entry for that: http://easyappointments.org/docs.html#1.2.0/faq.md

Most of the times you need to play around with the server and find what works the best for you, because not every server has the same configuration.

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
