### ISSUE TITLE
Unexpected issue with booking appointment after update to 1.2

### ISSUE THREAD

**Issue by shade73** [alextselegidis/easyappointments#248]
After we have updated to 1.2, we get an unexpected issue with trying to select date/time on the booking appointment page.

The error message is:  "The given $field_name argument does not exist in the database: availabilities_type"

I have trying running https://server/url/index.php/backend/update several times but to no luck. The backend/admin pages seems to work fine.

**Comment by alextselegidis** [comment]
Hmm, normally the  https://server/url/index.php/backend/update  should update the database structure ... 

But here is the MySQL change that you have to execute in order to fix this problem: 

```
ALTER TABLE emails ADD COLUMN availabilities_type VARCHAR(32) DEFAULT 'flexible' AFTER description;
```

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
