### ISSUE TITLE
Automatically populate the appointment end datetime in API.

### ISSUE THREAD

**Issue by danysz** [alextselegidis/easyappointments#251]
When I use the API to "save" a new appointment I have to pass few parameters.
One of the parameters is "end". The parameter is not relevant since the duration is "stabilized by the "service" anyway.

**Comment by alextselegidis** [comment]
This is true, but with Easy!Appointments an admin can always set the start and end arbitrary (which can happen in many occasions). This is why it is possible to set this up with REST. If this is not relevant in your case, try fetching the service duration first and then generate the appropriate end time.

I will leave this issue open so that the API does this automatically when the "end" date is missing. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
@alextselegidis I think that you could close this issue as it is resolved in #751.

**Comment by popod** [comment]
@alextselegidis ping :)

**Comment by alextselegidis** [comment]
@popod Thx!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
