### ISSUE TITLE
Multiple easyappointments Instances

### ISSUE THREAD

**Issue by tiagopotencia** [alextselegidis/easyappointments#256]
Hello! Easyappointments is a great software! Congrats!

I'm working in a project that a need to build a reservation for multiple stores. Something like this: https://www.treatwell.co.uk/

I note that easyappointments is great for "one instance" reservation. But i don't know if easyappointments is ready for a multi reservation service for multiple stores in a single application.

Sorry for my english. I hope i said what i'de like to say.

**Comment by alextselegidis** [comment]
Hello, I'm glad that you liked the app. Unfortunately the integration of a multi-installation system requires core-changes  in almost every section of the application which makes kind of hard to explain it here. 

Since you are a development I would recommend you to get some info about CodeIgniter and how it works and try to modify the app in order to suit your needs. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
