### ISSUE TITLE
UPGRADING TO 1.2 /update does not work

### ISSUE THREAD

**Issue by bcherup** [alextselegidis/easyappointments#258]
Issue 1 . Going to the /update link with the backend returns you to the login page.

Issue 2 . I'm unable to login as the page does not change but if I enter the wrong password it will notify

Why was this closed ? My issue was never resolved.

**Comment by alextselegidis** [comment]
Oh sorry, I accidentally closed the previous issue. 

So again on the problem, could you please post here the response of the login request, which you'll find in the browser's "network" tab of the developer tools. 

There might be probably error logs in /storage/logs directory, these will be useful as well. 

I'm going to need some feedback cause I cannot reproduce the error locally :(

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bkummerow** [comment]
I am having the exact same issue a @bcherup.  I am taken to the Backend Section page to login when visiting /index.php/backend/update.  My login does not work.  Using the Forgot your Password link will provide me with a new password, but when I use it, I do not get an error, but nor does it do anything either.  If I deliberately enter in an incorrect password, I get an error however.  If I enter in the correct password it just remains at the login page.

I have attached my log file (IP address redacted and URL changed) if that helps with troubleshooting this issue.

[easyappointments-error-log.txt](https://github.com/alextselegidis/easyappointments/files/824669/easyappointments-error-log.txt)

Thanks in advance for your help!

**Comment by xymantec** [comment]
I am dealing with a client who has this same problem, I have tried updating his installation but no luck I get sent directly to the login page. I need to get this resolved asap as the current install was compromised and being used to spam. (v1.1)

**Comment by alextselegidis** [comment]
@bkummerow Hi, I can see that the server responds with an error 500 status code in the login request but there is no error message because you provided the access log of your HTTP server. You will find further info in the error logs. 

`xxx.xxx.xxx.xxx - - [07/Mar/2017:07:58:38 -0600] "POST /index.php/user/ajax_check_login HTTP/1.1" 500 1843 "http://my.domain.com/index.php/user/login" "Mozilla/5.0 (Windows NT 6.1; `

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
