### ISSUE TITLE
Error enable google calendar sync

### ISSUE THREAD

**Issue by matteoventuri7** [alextselegidis/easyappointments#270]
After click Enable Syncronization

SecurityError: Blocked a frame with origin "/" from accessing a cross-origin frame.
&nbsp;/assets/js/backend_calendar_google_sync.js:50:37

TypeError: Cannot use 'in' operator to search for 'length' in FAILURE
&nbsp;/assets/ext/jquery/jquery.min.js:2:4002 w()
&nbsp;/assets/ext/jquery/jquery.min.js:2:2781 Function.each()
&nbsp;/assets/js/backend_calendar_google_sync.js:75:35 Object.success()
&nbsp;/assets/ext/jquery/jquery.min.js:2:27603 i()
&nbsp;/assets/ext/jquery/jquery.min.js:2:28369 Object.fireWith [as resolveWith]()
&nbsp;/assets/ext/jquery/jquery.min.js:4:13858 A()
&nbsp;/assets/ext/jquery/jquery.min.js:4:16146 XMLHttpRequest.()
![unnamed image](https://cloud.githubusercontent.com/assets/5465117/21227470/6dd8733e-c2da-11e6-89eb-e5c27a5caddb.png)

**Comment by alextselegidis** [comment]
The first error can be considered more as a warning cause it won't affect the functionality. The second though states that the google calendars couldn't be fetched due to an error with the API. Try to call the following URL in a new tab of the browser and post here the final result (after granting concern). 

http://your/ea/installation/url/index.php/google/oauth/{provider-id}

You can find your provider's ID from the database or the Network tab of your browser's developers tools after trying to enable the synchronization. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by matteoventuri7** [comment]
to page url http://your/ea/installation/url/index.php/google/oauth/{provider-id} I see google auth page asking me offline access to calendar. I grant it and then white page. Problem is not resolved.

**Comment by alextselegidis** [comment]
Is the DEBUG variable set to "true" in your root config.php file? If not set it to "true" and retry. I suspect that you should normally get an error instead of a white page, even though this is only an estimation. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by matteoventuri7** [comment]
I received that message:
Forbidden

You don't have permission to access /index.php/google/oauth_callback on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by alextselegidis** [comment]
Ok then I suppose there might be a misconfiguration in the Google API console. Try to set the complete URL in the "authorized redirect URIs" section of your OAuth2 Client Key. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by matteoventuri7** [comment]
Thank you. Hosting problem. This is not a bug.

**Comment by alextselegidis** [comment]
You are welcome :) 

Thanks for posting 👍

**Comment by UnAfraid** [comment]
I had the same issue, in my case the problem was .htaccess
