### ISSUE TITLE
Wrong address into Google event

### ISSUE THREAD

**Issue by matteoventuri7** [alextselegidis/easyappointments#279]
Hi, when someone takes new appointment i see a new event into my Google calendar but address is not customer's address but my company name.
![unnamed image 1](https://cloud.githubusercontent.com/assets/5465117/22073006/6cb0fa78-dda4-11e6-9391-14428cf68e16.png)

**Comment by alextselegidis** [comment]
Yeah this is right because the appointment must normally take place in the company's location and not at customer's address. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
