### ISSUE TITLE
Frontend book show available date

### ISSUE THREAD

**Issue by Dankof** [alextselegidis/easyappointments#280]
Hi all, 

In frontend booking, when you are going to select an "available", it shows to you automatically when "available" date its in the same month, but it the next available date its in other month that is not the current month it shows the current month with no available date.

I'm trying to change the code that if there aren't available dates on the current month, automatically show the month that there is available dates.

Any suggestion? 

Thank you

**Comment by alextselegidis** [comment]
Well this is a matter of preference. I totally understand your point but I sense that there will be some confusing with the customers that will see that they cannot head back to the current month just becose it's totally booked. Therefore the initial month selection depends on the current date and not in the availability. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Dankof** [comment]
Yes, but for example if it's january and only are available on march, user can go back to january and check by itself. Anyway, I'm trying to customize but do not find the key, any tip to change this??

Thank you!! :)

**Comment by alextselegidis** [comment]
Yeah but still I would rather expect to see the first month at the beginning and then navigate to a future date. To state this differently I think it's a matter of preference than right or wrong, so I'll leave it as it is for now. 

In order to change this though you will have to edit the frontend_book.js and frontend_book_api.js files.

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
