### ISSUE TITLE
Unable to login after fresh installation

### ISSUE THREAD

**Issue by jacob0davies** [alextselegidis/easyappointments#284]
Hi,

Great program, can't wait to get it working!!

So I installed vers 1.2 setup database config.php and corrected all the file permissions, that was just to get it installed. I am running CentOS 6 on a medium market VPS. We use CentosControlPanel (CWP) & PHP 7.1 + Apache 2.3.1

After entering the info, it takes us to login page, unfortunately it just won't let us in. We did the 'Forgot password' and sure enough it send a new password, but no joy - cannot login.

Any help would be appreciated :)

**Comment by l1m3se** [comment]
Have a same problem

**Comment by alextselegidis** [comment]
Hello, thanks for posting! 

Please open your browser's developer tools and click on the Network tab. Make sure that every network requests are recorded and try to login again. You will see that a `ajax_check_login` request is being logged every time you submit the login form. 

Post its data in this thread for further troubleshooting. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
I'm having the same problem. Not being able to log on once I created the account. It doesn't tell me that its the wrong password, which is does when I type in the wrong one. attached are the screenshots from my dev tools. I tried in other browsers & still nothing. Any thoughts?

<img width="1079" alt="screen shot 2017-02-12 at 3 17 20 pm" src="https://cloud.githubusercontent.com/assets/24920817/22865640/5fd87b78-f136-11e6-8b6c-6f3851d2d6e6.png">
<img width="1081" alt="screen shot 2017-02-12 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/24920817/22865639/5fd72494-f136-11e6-8fca-5589e9474360.png">

**Comment by alextselegidis** [comment]
Hello Jacob, thanks for the screenshots but I would like to see the response of `ajax_check_login` which is triggered once you click on the login button. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
Hi Alex, 

Sorry about that- attached are multiple screenshots of the ajax_check_login.

Hope this helps! I'm pretty new to all of this so still learning in case it's something I am doing wrong. 

What happens when I log in is that it just reloads to the user login page and prompts me to log in again. 

![screen shot 2017-02-13 at 1 47 26 pm](https://cloud.githubusercontent.com/assets/24920817/22897837/2f6c1c3e-f1f3-11e6-9fb7-89e803824dfc.png)
<img width="1029" alt="screen shot 2017-02-13 at 1 47 16 pm" src="https://cloud.githubusercontent.com/assets/24920817/22897838/2f7154ec-f1f3-11e6-883e-62b2531278d4.png">
<img width="1028" alt="screen shot 2017-02-13 at 1 47 09 pm" src="https://cloud.githubusercontent.com/assets/24920817/22897839/2f715730-f1f3-11e6-9131-cb35f2841c79.png">
<img width="1026" alt="screen shot 2017-02-13 at 1 46 59 pm" src="https://cloud.githubusercontent.com/assets/24920817/22897840/2f721260-f1f3-11e6-9d3b-033e541bf233.png">
<img width="1031" alt="screen shot 2017-02-13 at 1 46 47 pm" src="https://cloud.githubusercontent.com/assets/24920817/22897841/2f72d272-f1f3-11e6-8388-cd79b84b369e.png">

**Comment by viklas** [comment]
This might help with your debugging @alextselegidis (I had the same issue)

I used the fork below (and specific branch) to stand up a working instance last weekend, via a docker-compose deployment. I was experience that same 'takes me back to login screen' problem as @jacobandrews96 

https://github.com/rankun203/easyappointments/tree/feature-docker-compose

My gut says it's cookie related, but I stopped debugging when I found an alternative approach, that uses a slightly older code base. If I can remember any specific steps I took, I'll update this comment...was all of 7 days ago...can't be expected to remember last weekend's hacks.

On another note, easyappointments is awesome! Thanks so much for building it @alextselegidis

**Comment by jacobandrews96** [comment]
So, how would you recommend I fix, @viklas? Would It be standing up a working instance, or trying too (I'm pretty unfamiliar still). Would you be able to send me the older code base? I was thinking that too, but wasn't sure where I could find an older version of easy!appointments

**Comment by jacobandrews96** [comment]
Thank you so much for commenting as well!

**Comment by viklas** [comment]
If you follow these steps, you should be able to stand up a local instance (requires docker compose).
```bash
$ git clone https://github.com/rankun203/easyappointments.git
$ cd easyappointments
$ git checkout feature-docker-compose
$ mv src\config-sample.php src\config.php
```
Now we need to edit one line in the 'src\config.php' file (line 33).

Change "const BASE_URL  = 'http://url-to-easyappointments-directory';" to "const BASE_URL ='http://localhost:8001';"

Now go back to your console

```bash
 $ docker-compose up
```

Magic! (hopefully)

Like you said, something broke in newer codebase, since the fork above was taken. I'm sure it'll be fixed soon, but this approach worked for me.

**Comment by alextselegidis** [comment]
I think there's a misconfiguration in your server... could have to do with session storage but this is only a suspicion. By the way the `develop` branch has already a docker-compose configuration so you can use that to. 

* I'm suggesting that something's wrong with the server cause it worked within a docker environment ;) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
I'm running mamp, I've tried on ports 8888 and 80- any other suggestions?

**Comment by viklas** [comment]
Mamp? Not sure if that's a typo. If you haven't modified the docker-compose.yml file, the app should be running on port 8001.

**Comment by jacobandrews96** [comment]
I got it up & running on my friends computer (localhost) tried deleting my localhost and made a new one but still encountered the error. What are ways that I could fix my computer's configurations to have this work?

**Comment by jordics** [comment]
Same problem here. I'm suspect it's related to php7, because with an older version of php works fine

**Comment by alextselegidis** [comment]
@jordics I'm running the app with php7 with no problems 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by poltys** [comment]
Same problem here. Any help would be amazing ! 


![screenshot from 2017-03-15 15-27-12](https://cloud.githubusercontent.com/assets/12951939/23953283/775ca370-0994-11e7-8c65-9652ee6abc07.png)
![screenshot from 2017-03-15 15-28-00](https://cloud.githubusercontent.com/assets/12951939/23953284/775d2f98-0994-11e7-9635-39b5d47c3bde.png)
![screenshot from 2017-03-15 15-28-12](https://cloud.githubusercontent.com/assets/12951939/23953285/775ec8bc-0994-11e7-94fa-e3de97c89c01.png)

**Comment by poltys** [comment]
FYI - doesn't work with php7 but works with php5.

**Comment by alextselegidis** [comment]
Strange, cause I'm running the app with PHP 7 without issues. Could somebody please send me with pm his server credentials (ssh)? I'd like to take a look and verify if this is really a bug or if I have to change something in the codebase so that it doesn't happen. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by scottatron** [comment]
I'm seeing the same problem—it appears to be because the session cookie is being reissued on each request.

Looks like it is probably due to bcit-ci/CodeIgniter#4874 which was [fixed in 3.1.2](https://www.codeigniter.com/user_guide/changelog.html#bug-fixes-for-3-1-2)

The [upgrade path](https://www.codeigniter.com/user_guide/installation/upgrading.html) looks pretty straight forward, so I'm happy to give it a shot, and open a PR.

**Comment by alextselegidis** [comment]
I'm really interested to try this out, thanks @scottatron!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sbedarkar** [comment]
Hi, I am facing a similar issue with the installation. Unable to login after creating an account. I can see the database entry for the account created
 
Any suggestions

Note: this is with version easyappointments_1.2.0

**Comment by alextselegidis** [comment]
@sbedarkar Please send me your installation URL and some test credentials to try at alextselegidis@gmail.com

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sbedarkar** [comment]
I tried to use the latest version easyappointments_1.2.1 2 , after editing config.php got the following error : 
Warning: Uncaught Exception: Session: Configured save path '/Users/.../easyappointments/application/config/../../storage/sessions' is not writable by the PHP process. in /Users/.../easyappointments/system/libraries/Session/drivers/Session_files_driver.php:143 Stack trace: #0 [internal function]: CI_Session_files_driver->open('/Users/r_bedark...', 'ea_session') #1 /Users/.../easyappointments/system/libraries/Session/Session.php(143): session_start() #2 /Users/.../easyappointments/system/core/Loader.php(1281): CI_Session->__construct() #3 /Users/.../easyappointments/system/core/Loader.php(1174): CI_Loader->_ci_init_library('Session', 'CI_', NULL, 'session') #4 /Users/.../easyappointments/system/core/Loader.php(1037): CI_Loader->_ci_load_stock_library('Session', 'Session/', NULL, NULL) #5 /Users/r_bedar in /Users/.../easyappointments/system/libraries/Session/drivers/Session_files_driver.php on line 143

Fatal error: session_start(): Failed to initialize storage module: user (path: /Users/.../easyappointmentsapplication/config/../../storage/sessions) in /Users/.../easyappointments/system/libraries/Session/Session.php on line 143
A PHP Error was encountered
Severity: Error

Message: session_start(): Failed to initialize storage module: user (path: /Users/.../easyappointments/application/config/../../storage/sessions)

Filename: Session/Session.php

Line Number: 143

**Comment by alextselegidis** [comment]
@sbedarkar Thanks for providing the logs. 

You have to set write permissions to the `storage` directory. 

Only then can Easy!Appointments write its log files and session info into that directory.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sbedarkar** [comment]
changed the permission using chmod a+w for the storage folder located at   Users/.../easyappointments/application/config/../../storage/sessions. 
No change same error

**Comment by patriciojlg** [comment]
I had the same problem
I turned off the pagespeed module and it worked
(pagespeed is a module for compress and minimize js, css, cache-debug, and other)

**Comment by discry** [comment]
fixing the settings on storage directory to write permissions fixed login issues for me

**Comment by alextselegidis** [comment]
Some background info so that everyone knows what the actual problem is. 

Different servers have various configurations so that session handling takes place in different formats, something that leads to problems that are hard to debug and to resolve. 

Therefore Easy!Appointments is using a pre-configured directory to store the session files and that is the /storage/sessions directory. 

The only thing that you have to make sure is that the storage directory is writable. If you are not sure which permissions to set, try 777 as this will always work. 

So the first time you try to log in, the app tries to create a session and that fails as the directory is not writable. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>


The app uses a custom location for storing session information cause different servers have different settings and can lead to unexpected issues.

**Comment by acaciomartins** [comment]
tks tks tks, fixing the settings on storage directory to write permissions fixed login issues for me..

uhuuuuuuuuu
