### ISSUE TITLE
Emails Not Being Sent

### ISSUE THREAD

**Issue by oxhey** [alextselegidis/easyappointments#30]
I have setup easyappointments , but when an appointment is booked , an email isnt sent to the customer to tell them of their appointment

**Comment by alextselegidis** [comment]
Can you check that the email function operates correctly in your server? You should also enable error logging just in case there is a hidden error. 

https://easyappointments.wordpress.com/2015/04/27/easyhints-enable-error-logging

**Comment by oxhey** [comment]
Is there any thing I need to do to setup email with easy appointments like a config file?

**Comment by alextselegidis** [comment]
Easy!Appointments is using the popular PHPMailer library. You can modify the /application/libraries/notifications.php file and setup PHPMailer according to your mailing system (for example you might need to use SMTP).

**Comment by nossileee** [comment]
Hello Alex,

I am having difficulties sending emails, I have tried several times, installed and deactivated the application, recruited database, researched some solution and found nothing.

I found this message of yours:

https://github.com/alextselegidis/easyappointments/issues/30

alextselegidis commented on 16 Jun 2015
The Easy! Appointments is using the popular PHPMailer library. You can modify the /application/libraries/notifications.php file and configure PHPMailer according to your mail system (for example, you may need to use SMTP).

However, this directory does not exist, the closest thing I found was this:
scheduling \ application \ config \ email.php

Is it within this file that I should edit with the information on my server for it to work?

Original is thus:

<? php defined ('BASEPATH') OR exit ('No direct script access allowed');

// Add custom values ​​by setting them to the $ config array.
// Example: $ config ['smtp_host'] = 'smtp.gmail.com';
// @link https://codeigniter.com/user_guide/libraries/email.html

$ config ['useragent'] = 'Easy! Appointments';
$ config ['protocol'] = 'mail'; // or 'smtp'
$ config ['mailtype'] = 'html'; // or 'text'
// $ config ['smtp_host'] = '';
// $ config ['smtp_user'] = '';
// $ config ['smtp_pass'] = '';
// $ config ['smtp_crypto'] = 'ssl'; // or 'tls'
// $ config ['smtp_port'] = 25;

I tried to configure it like this:

$ config ['useragent'] = 'Easy! Appointments';
$ config ['protocol'] = 'smtp'; // or 'mail';
$ config ['mailtype'] = 'html'; // or 'text'
$ config ['smtp_host'] = 'mail.smtp2go.com';
$ config ['smtp_user'] = 'bhlfitne';
$ config ['smtp_pass'] = '7m4z51HVls';
$ config ['smtp_crypto'] = 'tls'; // or 'ssl'
$ config ['smtp_port'] = 2525;

Because the data is from my smtp2go.com email forwarder, it's the same as I use on my site, to forward emails to my clients when they place orders on my site.

But it gives errors and does not work either.
Could you help me at least with this solution?
I searched all over the internet and found no solution whatsoever.

Thank you very much for your attention.

**Comment by nossileee** [comment]
Original is thus:

<? php defined ('BASEPATH') OR exit ('No direct script access allowed');

// Add custom values ​​by setting them to the $ config array.
// Example: $ config ['smtp_host'] = 'smtp.gmail.com';
// @link https://codeigniter.com/user_guide/libraries/email.html

$ config ['useragent'] = 'Easy! Appointments';
$ config ['protocol'] = 'mail'; // or 'smtp'
$ config ['mailtype'] = 'html'; // or 'text'
// $ config ['smtp_host'] = '';
// $ config ['smtp_user'] = '';
// $ config ['smtp_pass'] = '';
// $ config ['smtp_crypto'] = 'ssl'; // or 'tls'
// $ config ['smtp_port'] = 25;

**Comment by nossileee** [comment]
Original is thus:

<? php defined ('BASEPATH') OR exit ('No direct script access allowed');

// Add custom values ​​by setting them to the $ config array.
// Example: $ config ['smtp_host'] = 'smtp.gmail.com';
// @link https://codeigniter.com/user_guide/libraries/email.html

$ config ['useragent'] = 'Easy! Appointments';
$ config ['protocol'] = 'mail'; // or 'smtp'
$ config ['mailtype'] = 'html'; // or 'text'
// $ config ['smtp_host'] = '';
// $ config ['smtp_user'] = '';
// $ config ['smtp_pass'] = '';
// $ config ['smtp_crypto'] = 'ssl'; // or 'tls'
// $ config ['smtp_port'] = 25;

**Comment by nossileee** [comment]
Because the data is from my smtp2go.com email forwarder, it's the same as I use on my site, to forward emails to my clients when they place orders on my site.

But it gives errors and does not work either.

Could you help me at least with this solution?

I searched all over the internet and found no solution whatsoever.

Thank you very much for your attention.

**Comment by dhanya-12345** [comment]
the file s not decrypted while sending the mail how to resolve the issue
