### ISSUE TITLE
Back-end login does not work with PHP 7.1

### ISSUE THREAD

**Issue by piyushmantri** [alextselegidis/easyappointments#306]
I have installed and configured the config.php file.
When I try to log in using my admin credentials, there is no response from the system and the form resets.
Also, there's no ajax_check_login in network tab. It appears for few milliseconds and then the form resets.
Please help.
I have xampp version 3.2.2 (php 7)  running on my system.
![image](https://cloud.githubusercontent.com/assets/13727284/24374925/34c841d0-1354-11e7-9a3c-287ab5f4fa0c.png)

**Comment by PandaHugMonster** [comment]
Can confirm! Have the same issue. Arch Linux, PHP 7

Redirects

"GET /index.php/backend HTTP/1.1" 302 -

**Comment by dylankolson** [comment]
@PandaHugMonster @piyushmantri quick fix is to change your php version, I changed mine to 5 and worked fine.

**Comment by piyushmantri** [comment]
Yeah.. its working on php 5. But whats the problem with php 7?

**Comment by PandaHugMonster** [comment]
@dylankolson With all my respect, it's not a quick fix if you have all your projects are developing on your machine with PHP7. 
But thank you for the suggestion.

**Comment by peterleblanc** [comment]
I am having the same issue.  I started with E!A 1.1.1 then upgrade to 1.2.0.alpha then upgrade to 1.2.0.beta all with no problems then when I went to upgrade to 1.2.0 I ran into not being able to login anymore.  Did a password reset got the email and tried to login and it just refreshes the login page, when I type the wrong password intentionally I get a box stating "Login failed, please enter the correct credentials and try again.".  This leads me to believe it knows the password is correct but it can't get past the login screen.  

I have switched my php versions from 5.4.16 to 5.5.38 to 5.6.30 to 7.0.17 to 7.1.3 with a system reboot each time with no luck of getting in.  If I do a fresh install of 1.2.0 I can't get the front or login page to even load, which is why I started down the path with older version and upgrade until the error is found.  I am running ‪CentOS Linux 7.2.1511 with Plesk Onyx Version 17.0.17 Update #22 on a dedicated machine.

Any ideas?

**Comment by shade73** [comment]
I have the same issue, cannot access backend anymore. Worked fine for long time but after the server was lifted from PHP 7.0.16 to 7.1.3 it is no longer possible to login to the backend.

I if write a wrong password it correctly tell me that username/password is wrong, but if I enter the correct password it just reloads the page.

**Comment by alextselegidis** [comment]
For the users that have a problem under PHP 7 try to set the sessions.save_path php.ini property on your server. 

For the users of PHP 7.1 the problem must lie in a different location, I haven't troubleshooted it yet. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sacmt-hciie** [comment]
mysql_connect() has been deprecated as of php5.5 and gone in php7

**Comment by alextselegidis** [comment]
By default version 1.2 uses the mysqli extension so this shouldn't be a problem. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by shade73** [comment]
What is the solution for us php 7.1 users?

**Comment by shade73** [comment]
Update to 1.2.1 :)

**Comment by vm-alex** [comment]
This is still a problem with 1.4.1, was this a confirmed fix?

**Comment by abdennour** [comment]
Yes it's still an issue. 
Login succeed as per the logs, but no redirects.

I am pretty sure that all these pains because of the missing of proper containerization. 
The existing Dockerfile is very orphan: no composer, no node, no npm.

We love this software because its features but now, it's pain in the neck because of the in-compliance with release engineering principles.

**Comment by everton** [comment]
I don't know if this will help anyone, but in my case, the same behavior was happening because the web server user (www-data in the case of Apache under Debian) was not allowed to write in the storage/sessions folder. 

The application tries to write a file there for the sessions created and I discovered the problem after enabling the logs where I could find a message like:

> "Session: Configured save path '...' is not writable by the PHP process.

So, if you are not been able to log in after the installation, check the permissions of the storage/sessions folder, maybe this will work for you (I'm using the last commit from the main branch, which says "Release v1.4.3" and with PHP 8.2.5 + Apache on a Debian system)
