### ISSUE TITLE
Double booking when two users try to book the same appt hour and at the same time.

### ISSUE THREAD

**Issue by oxhey** [alextselegidis/easyappointments#31]
Iv found that it two appointments are booked for the same time at the same time , it double books the provider. Is there a way to stop this happening?

**Comment by alextselegidis** [comment]
How is this possible? Can you tell me how I can reproduce this problem?

**Comment by oxhey** [comment]
Open two bookings (two browser windows side by side) , choose the same date and time . Go through all the steps until confirmation. Click one , and then the other . It double books.

**Comment by alextselegidis** [comment]
You are right, marked for v1.1

**Comment by bosz** [comment]
I had same issue too but had a workaround by the method below. 

I think you can modify the database structure.

That is, make the (start_datetime, end_datetime, id_services) pair unique so that even if they succed to click book at the same time, the database will reject one of them once the other has already been booked. 

You can use this alter statement. 
**ALTER TABLE `ea_appointments` ADD UNIQUE `appointment_time_id`(`start_datetime`, `end_datetime`, `id_services`);**

At this stage, you may want to add a check if the database insertion fails. 

Hope that helps.

**Comment by alextselegidis** [comment]
Interesting idea, but either way you will have to check if there is already an entry with conflicting start and end time.

**Comment by bosz** [comment]
You are right alex, my method is just a workaround.

**Comment by alextselegidis** [comment]
:+1:

**Comment by bosz** [comment]
alex, there are two ways i think we might be able to handle this situation. 

I notice that before booking, an ajax request is made to verify that that time is available. The booking could also be made using that same ajax request. Ie, check and book. 
So booking will no longer be by the normal post request but now by that same ajax that checks if the time is available. 

What say you?

**Comment by alextselegidis** [comment]
Hi, I have recently changed the booking procedure to an AJAX call, I will just have to add like you said the check exactly before the registration is done, and return an error otherwise.

**Comment by FelixRolfBossner** [comment]
Dear Alex,

first of all thank you for your wonderful software ! It was and still is a big help for us (a small municipial public administration) in times of Corona. However, we still encounter the described double-booking bug with the "Any Provider" functionality both within our EA-installation and when simultaneously booking from two browser instances within the https://demo.easyappointments.org/ demo-version. Due to our organisational structure, we cannot allow customers to choose their appointment based on the respective provider/desk, but only based on the respective service (which is why we cannot switch from the "Any Provider"-preselection. Due to the large number of customers, we have around 40 double bookings/week.
Is there any recommended quick fix for this problem ? 

Best regards and thank you again for providing such a useful, accessible  and thought-out solution via Open Source ! =)
