### ISSUE TITLE
ajax_change_language error 

### ISSUE THREAD

**Issue by bullmoose20** [alextselegidis/easyappointments#310]
Why would ajax_change_language need to access the roles_model and why is it failing on a foreach line? More details on google groups.

**Comment by alextselegidis** [comment]
Hi there, 

any back-end API request makes a check in the roles db table in order to verify that a user has the required permissions for the current task. 

I understand that this may be unnecessary for changing the language but on the other hand there is no drawback at doing it at all. 

Since you are getting errors I'm supposing that something was not correctly set in your database.  Check the assets/sql/structure.sql and assets/sql/data.sql for further information on how a fresh installation schema must look like. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bullmoose20** [comment]
Once I turned off debugging, I was able to change languages. Strange, but for now that's fine for me.

**Comment by alextselegidis** [comment]
I'm guessing that PHP warnings broke JSON responses from server and thus sutff may not worked out for your installation.  

Feel free to post here again if you continue having problems. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
