### ISSUE TITLE
How to set the timezone from the user booking the apt. 

### ISSUE THREAD

**Issue by briankwest** [alextselegidis/easyappointments#313]
I want to use this to schedule phone calls, I have clients all over the globe that need to be able to see the calendar in their local timezone so they can pick an appropriate time.

Any hints?

/b

**Comment by alextselegidis** [comment]
This is a really complicated task to do as it requires a lot of refactoring in every section of the app. Unfortunately it won't be implemented in the near future due to lack of time, but I will mark it as  a feature request for an upcoming release.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by briankwest** [comment]
I've been reviewing how to add this feature, if I get time I may submit a patch.

**Comment by zaidjamal** [comment]
This feature request is big for me as well, and for the same reasons. Best of luck sorting out how to do this!

**Comment by alextselegidis** [comment]
Update, this will be a feature of v1.4

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by viktorix** [comment]
Thanks!

**Comment by yrammos** [comment]
Gosh, this is wonderful to hear… Lack of timezone support is an ironic dealbreaker nowadays in an otherwise terrific app.

**Comment by alextselegidis** [comment]
Committed on develop

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by yrammos** [comment]
My fork implementing this is now available at github.com/tekhnee/appointments. 

I'm not submitting this as a PR because the modifications are massive. But you may cherry-pick ideas and patches as you deem fit.

A (pre-production) site is online at meeting.tekhnee.org. Please avoid actually booking too many appointments because they will end up in my calendar...

**Comment by Valkyrurr** [comment]
Wow! Congrats, @alextselegidis ! Just saw this project and I wonder how long it usually takes to have a stable version of the `develop` branch?
