### ISSUE TITLE
Deleting provider doesn't work

### ISSUE THREAD

**Issue by ahmedi2l** [alextselegidis/easyappointments#336]
Hi,
By testing version 1.2.1 of the software, I notice that deleting a provider doesn't work. It seems to be a bug.

**Comment by eheintzmann** [comment]
Same problem with secretary on 1.2.1 version

**Comment by ahmedi2l** [comment]
Deleting consumer also doesn't work

**Comment by alextselegidis** [comment]
Are there any messages in the error logs? Which PHP version are you using? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by eheintzmann** [comment]
tried with php 7.0.10 and 5.6.25 (on wamp server 3.0.6).

Mysql log (french):
2017-06-15T08:22:15.627672Z 0 [Warning] wampmysqld64: Arrêt forcé de la tâche (thread) 3  utilisateur: 'easyappointments'

**Comment by ahmedi2l** [comment]
There is no  error.
I'm using php version 5.6.30 on debian Jessie

The problem may be related to javascript because when we click on the delete button nothing happens.

**Comment by BonjourUnivers** [comment]
solved it, the problem comes from the translation file : 
We are FRENCH (this is how i found it, the issue only occurs for french people^^), and the 'cancel' translation exists twice, one of them refers to 'Supprimer' (french for 'delete')
You will notice that in the french version, there is no cancel button, because they are merging due to the wrong translation, but only the cancel event is bound, this is how you get a cancel action on the delete button.
So, just delete l91 (it should be $lang['cancel']='Supprimer';) in in the french translation_lang.php file, and the correct translation will allow the buttons to generate properly, and therefore, the events will be bound and the ajax call made.

**Comment by ahmedi2l** [comment]
Bravo @BonjourUnivers for finding out what was wrong.
It works for me now.
Can you make a pull request?

Thanks

**Comment by alextselegidis** [comment]
Hey, this happened before! 

Is this pull relevant? https://github.com/alextselegidis/easyappointments/pull/329

I have to change the way translation strings are being used in modals .... 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I corrected the issue in develop branch. It will be released with v1.3.

Commit: fe5341a0af2951d7ec31906b038eecab7f882a39

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
