### ISSUE TITLE
Skip the first booking step when only one service and one provider are available. 

### ISSUE THREAD

**Issue by dipiana** [alextselegidis/easyappointments#349]
Hi,

Is there any way to skip the first page ("Select Service & Provider") when there is only one service and one provider available?
In my case it would confuse customers.
If not - is there any file I can change to make this adaptions myself?

Thanks in advance!

**Comment by alextselegidis** [comment]
Hi, yes this is a good suggestion! 

You can change this behavior by adding some JavaScript in frontend_book.js that will check the number of option during initialization and skip the first page if needed. 

The offending dropdowns are the #select-service and #select-provider. 

You will just have to make the following ckeck `$('#select-service option').length === 1 && $('#select-service option').length === 2` (providers will always have two options because of the "Any Provider" entry). 

Take a look at the `book.php` view file for further info on the HTML markup. 

Pull requests are always welcome :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by TVBZ** [comment]
Hello

Just discovered EasyAppointments today.. Exciting, thumbs up! :)

I have same situation. I want to skip step 1. I have changed the book.php view file but I'm a bit lost in the js part. Can you elaborate where/how to implement the check?

Many thanks!

**Comment by alextselegidis** [comment]
@TVBZ the frontend_book.js has logic on proceeding with steps (back and forth). 

You can find this and tweak so that it ignores the first step. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jdaviescoates** [comment]
Given I'm trying to recreate a Calendly-like experience I would also love to be able to skip the first step.

Another way to achieve the same thing, which I think would be even nicer (and more Calendly-like), would be for people to be able to go domain.tld/user and then get a page that just presents all the services available from the specific user.

**Comment by vitormattos** [comment]
A suggested solution is:

- Define a unique slug for each service
- Define a unique slug for each customer
- Create a route `/<service>/<customer>`

This route will not display step 1 of the wizard and start the wizard at step 2.

The creation of the URL at first will be manual.

Solve the need? If so, I can send a pull request by implementing it.

@alextselegidis can I send a PR implementing this?

**Comment by vitormattos** [comment]
I started the changes by reviewing the unit tests. #1042

**Comment by vitormattos** [comment]
Updating the progress:

I created another PR implementing test coverage for customers and services #1044

**Comment by vitormattos** [comment]
Done, closed in #1048

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
While this might be a nice addition for some people, I think it's not always wanted. Two reasons:

- It's desirable to see what kind of booking you make an appointment for and step 1 shows it.
- Information about duration and location is at the bottom of step 1 and would get lost.

I wouldn't want to have this addition, so I think it should be an option in the settings.
