### ISSUE TITLE
Email notification problem

### ISSUE THREAD

**Issue by fkolar** [alextselegidis/easyappointments#360]
Just installed easyappoitments and I must say great work. easy to use. 

But there is one thing I cannot get to work is email notification, what should be the system readyness so it can send email notification? 
I dont see in config.php any detail to enter smtp servers. 

When user enters the appointments I assume it send email confirmation right?

Thanks, 
Frank

**Comment by alextselegidis** [comment]
Hello Frank, 

email server configuration is hidden inside another file: `application/config/email.php`

Feel free to adjust it as described here: https://www.codeigniter.com/user_guide/libraries/email.html

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by fkolar** [comment]
Great. Thank you..

**Comment by 3KQgt0Cl** [comment]
What are the server requirements for this to work? I am struggling setting this up with no resaults.

I would like to avoid external SMTP servers.

What would be the steps to set this up?

Please help, I am hopeless!

**Comment by alextselegidis** [comment]
@3KQgt0Cl You will need to have the php mail function being configured correctly in order to send emails without SMTP. 

Unfortunately there are different ways to do this and I cannot go through all of them here but there are also plenty of resources online depending on the environment your are using. 

http://researchhubs.com/post/computing/linux-basic/enable-php-mail-function-to-work-on-ubuntu.html

https://www.digitalocean.com/community/questions/php-mail-function-enable

https://stackoverflow.com/questions/5773288/configure-wamp-server-to-send-email

You will also need a test script that sends a mail with php to check if this is working. 

https://www.conetix.com.au/support/article/simple-php-mail-test

Hope that helps! :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by 3KQgt0Cl** [comment]
@alextselegidis Fixed by using Gmail's SMTP. :)
