### ISSUE TITLE
Only allow appointments for a few weeks in advance.

### ISSUE THREAD

**Issue by robertobarlocci** [alextselegidis/easyappointments#365]
Hi Alex,

thanks for the great app, saved me a lot of time! =)

Is there any way to restrict creating new appointments more than 4 weeks in advance?

Any ideas how this could be added?

**Comment by alextselegidis** [comment]
Hi! You can modify the `application/controllers/Appointments.php` file and the `ajax_get_available_providers` method to turn the book advance timeout into days instead of minutes. 

I'll mark this request as a feature request that can be integrated in a future release. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by TVBZ** [comment]
I second this feature. I want to have bookings for no more then 2 weeks in advance.
Any news on this feature? Or some example how to modify it would be great..

Many thanks!

**Comment by Connor1st** [comment]
Hi everyone!
I have pasted the code below into /application/controllers/Appointments.php underneath the code that removes appointments too close to now. (Commented with "//If the selected date is today, remove past hours.......")

`          	// If the selected day is beyond the advance booking limit hide all time-slots
/**/        if (date('Y-m-d', strtotime($this->input->post('selected_date'))) >= date('Y-m-d', mktime(0, 0, 0, date("m") , date("d") + 14, date("Y"))))
            {
                foreach ($available_hours as $index => $value)
                {
                        unset($available_hours[$index]);
                }
            }`

14 is the number of days, change this to suit your requirements. Hopefully, alextselegidis will be able to do this much better than me and add it as a variable we can change via the interface.

**Comment by alextselegidis** [comment]
@Connor1st thanks for posting your solution. 

I also agree that a future release must include better configuration possibilities from the backend settings page. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
