### ISSUE TITLE
Cannot delete element if I use "french" language in config.php file

### ISSUE THREAD

**Issue by philouphil** [alextselegidis/easyappointments#369]
Hello,

All is said, is there an explanation that when I use the french language I can't delete client or service or user ?

If I let const LANGUAGE  = 'english'; everything is fine
 const LANGUAGE  = 'french'; => problems

Thanx !

**Comment by alextselegidis** [comment]
Hello @philouphil, 

this issue is already reported and is already fixed in the develop branch of this repository. 

As a quick workaround you can change the french translation for delete (which is currently the same as cancel) and this is what makes the problem. 

Offending file; `application/language/french/translation_lang.php`. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
