### ISSUE TITLE
AJAX Error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jihadismail8** [alextselegidis/easyappointments#370]
after deploying on my server , i am getting this message everytime i try to change the language , but on localhost everything is working fine ?? what the problem could be ?  i added the url into the Config , and i made few modifications in the interface design , but i can not find out what is making this AJAX problem  ?  any help or at least a hint of what is causing this problem would be appreciated :) thanks

**Comment by alextselegidis** [comment]
Please check for error logs in storage/logs directory or directly on your server. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by gilbertngandu** [comment]
Hi, I had the same problem. The issue is caused by the base URL try this in the config.php file in the root
`
define('APP_URL', ($_SERVER['SERVER_PORT'] == 443 ? 'https' : 'http') . rtrim("://{$_SERVER['SERVER_NAME']}".str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']),'/')); 

const BASE_URL      = APP_URL;
`
