### ISSUE TITLE
sso for easyappointments?

### ISSUE THREAD

**Issue by dukados** [alextselegidis/easyappointments#384]
Hi i am very impressed by your application.
got it installed and working.

i have a question: is there a way to implement sso (with google authentication) ?
meaning: sso for the providers, not for clients.
where should i start?

**Comment by alextselegidis** [comment]
I would suggest that you start taking a look at the documentation of CodeIgniter so that you get a better understanding of how the app is structured and works. Then you have to create a Google project and enable the corresponding API that you'll use later on. 

Finally you will have to adjust the code that is releant to the login part within the app and add the possibility to auth with google. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
