### ISSUE TITLE
Table cells on the calendar should be clickable

### ISSUE THREAD

**Issue by aqua4** [alextselegidis/easyappointments#389]
It would be so much better if calendar cells were clickable.
On click, if the selected slot is free, the 'New appointment' window with selected date and time will be shown.

**Comment by VyReN** [comment]
Check out the latest alpha, this functionality exists!

**Comment by alextselegidis** [comment]
Correct, since Easy!Appointments v1.3 this feature is included.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
