### ISSUE TITLE
Customer Name in Appointment Title

### ISSUE THREAD

**Issue by whitespring** [alextselegidis/easyappointments#419]
Hi, 

I struggle with figuring this out:
All appointments in google calendar only get the customer as a guest with email but we dont get the name. How do I add the customer name to the title and all the other info to the comments field? 

Thanks so much for your help.

**Comment by alextselegidis** [comment]
I think I had similar issues in the past and the problem is actually by Google.  It will not let you display the names although they are being properly set. 

Being said it can also be that the API was changed and the Easy!Appointments has to be updated accordingly. I didn't had the time to check this yet ... 

As a workaround I would suggest that you add the customer names (and further info) in the notes of the event. 

For this you will need to update the `src/application/libraries/Google_sync.php` file.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
