### ISSUE TITLE
Synchronization errors with Google calendar

### ISSUE THREAD

**Issue by gireuno** [alextselegidis/easyappointments#427]
Hello! When a person fixes an appointment the synchronizes on my google calendar is an hour later. The same is  when i set not available times, on google calendar are synchronized one hour later both start and the end

**Comment by alextselegidis** [comment]
Hello @gireuno, the problem there is that your server uses a different timezone than your google calendar. 

To sync this app you can try adding the following command at the top of the root index.php. 

`date_default_timezone_set('America/Los_Angeles');`

You can find further info in php.net http://php.net/manual/de/function.date-default-timezone-set.php

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bobziroll** [comment]
Has there been any updates on this? I'm successfully pulling in events from a Google Calendar, but they are offset in E!A by 7 hours. (An event I add to Google Calendar at noon shows up in E!A at 7pm).

I've added the `date_default_timezone_set('America/Denver')` to both the `index.php` and `config.php` files, as well as my MAMP's `php.ini` file. Feeling pretty stuck now.

**Comment by alextselegidis** [comment]
Hi @bobziroll, make sure that you restart your server after changes in php.ini. 

Also try  the `phpinfo` command to see if the server runs in the same timezone as you are (`date.timezone` property)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by egratzl** [comment]
Hi Guys,
after few hours. I've got it. Google plugin is the right place to tiny rework:
Open:
application/libraries/external/google-api-php-client/Google_Client.php

Edit:
`if (! ini_get('date.timezone') && function_exists('date_default_timezone_set')) {
  date_default_timezone_set('UTC');
}`

Change to:
`if (! ini_get('date.timezone') && function_exists('date_default_timezone_set')) {
  date_default_timezone_set('UTC+1');
}`
Here you can choose UTC+ (your time shift).
DONE!

Now your sync to google contain correct time.
This workaround is useful if your php.ini contains wrong timezone and you can't change it because of WebHosting.

Good luck
