### ISSUE TITLE
Use PHP integrated PHP algorithms for hashing user passwords.

### ISSUE THREAD

**Issue by simmonspaul** [alextselegidis/easyappointments#439]
The use of both a hashed password and salt has been depreciated in favor of using stronger self-salting algorithms.

see php password_hash
https://secure.php.net/manual/en/function.password-hash.php

---
Remediating this will assist other applications that need to integrate user credentials.

Many thanks

**Comment by alextselegidis** [comment]
Hi @simmonspaul, you are right this is a good thing to do, I will change this for v1.4

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by simmonspaul** [comment]
This should help https://github.com/benedmunds/CodeIgniter-Ion-Auth 
I'm going to be doing some playing around with it.

**Comment by alextselegidis** [comment]
Hi @simmonspaul, thanks for your message. 

Feel free to make a pull request if you reach a fully functional state. 

Greetings! 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Quick update on this ticket. 

In order to update the passwords, every time the user logs in we will need to write the updated hashed password string to the database and ditch the salt value as it is not needed anymore. 

Since in the following Easy!Appointments releases there might be an upgrade to another framework that handles this differently, I will skip performing this actions for v1.4.0 and perform them once when the right time comes. 

Thanks for posting this nevertheless! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
