### ISSUE TITLE
Too many required fields

### ISSUE THREAD

**Issue by d1a8lo24** [alextselegidis/easyappointments#44]
Before anything great application just a few things to consider.

To make things easier on the installation process, do not request or require so much information. 
Last Names and Phone numbers in certain sections should be required but not in all specially in the installation process. Let the company or person fill out that information once they get into the system.

Same thing for adding users, last names and phone numbers should not be required the email is more than enough.

It is a great way to keep things organize but most of the personal information should be optional.

So far things look good I have stumble upon some issues but I still have to see if they are related to my share server.

Again great application.

**Comment by alextselegidis** [comment]
Hello, I'm glad that you liked the project :)

The thing is that the installation required fields are the minimal ones because the app logic requires for every backend user the following values: first name, last name, phone, username and password. 

The company info are needed for the email notifications and some other meta info displayed in various sections, so I cannot remove them.

So users can actually type in this mandatory data but after the installation procedure they can go to the settings page and complete their personal information.

**Comment by d1a8lo24** [comment]
I didn't say to remove them, but they shouldn't be required, is just a suggestion from some one that has created many apps with similar functions and that has tested a lot of them. 

The last name and phone number shouldn't really effect the application logic, since these two fields are for either displaying purposes or being searched, so if they are not available they really don't affect how the application works. 

Really simple example, look at any smart phone and when creating a contact there is only a few things you need to add to create that contact, name and phone or emails that's it from there you can create reminders, set up appointments etc... 

As far as the installation goes, the same thing too much information being required most of it can have defaults. All you really need is a database connection and create the admin user. If the application really requires the rest of the info just have defaults like:

Company name: ACME
Address 2222 Acme rd. New York, NY 55555
Phone: 555 555 555

But is up to you on what you decide to do is your application but sooner or later people will bring up such things. I my self was getting a little frustrated with the installation.

I can tell you right now that after installing hundreds of apps for friends, clients and myself there is only one application that I can say I love they way it installs and its call KOKEN. check it out to get some ideas.

**Comment by alextselegidis** [comment]
That sounds pretty reasonable.... I'll give some thought for sure. But thank you for the feedback anyway :)

**Comment by alextselegidis** [comment]
After considering your suggestion I decided to leave the all the fields in the installer. The reason is that many users will not really think of going to the settings page and set their data. I know this might sound a bit weird but I get a lot of questions about really basic stuff that anyone would found just by navigating to the backend.

So by leaving the fields there I'll be sure that the user has filled the required data just before starting to use the app. 

PS: I even added a dummy service and provider so that people can try the booking wizard without needing to setup their own and yes this was asked a lot :/

**Comment by olsonpm** [comment]
I got here because I'm confused what company is for and why it's required.  I'm installing easyappiontments since I'm looking for a self-hosted calendly alternative to book general personal appointments and sync it with my google calendar.  The concept of a company in my case doesn't make sense.  If that means easyappointments isn't intended for me then I understand and that's perfectly fine.  I suppose I'd just recommend an explanation in the web app or the documentation on what these fields are for so users have a better understanding.

Thanks for this tool.  I'm looking forward to seeing how it works :)
