### ISSUE TITLE
Time Zones for appointments not changing

### ISSUE THREAD

**Issue by NickSchick** [alextselegidis/easyappointments#445]
Situation: 
Server time is set via php.ini to Europe/Berline.  The Providers -> Working Plan is set to 9:00am-5:00pm 
--
When user from New York accesses the booking system to create an appointment he/she is offered times of 9:00am - 5:00pm.
Shouldn't they be offered 3:00am - 11:00?

Am I missing something?

**Comment by alextselegidis** [comment]
It depends, the customer from New York is booking times at the place the provider is located, so all times there must be in the Europe/Berlin timezone.

If the appointment though is something that will require that the customer stays in New York and the Provider stays in Berlin then you are right the times should be different for the customer. 

The problem is that timezones are not supported yet by the system and will be implemented in a future release.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by M4rt1n17** [comment]
> The problem is that timezones are not supported yet by the system and will be implemented in a future release.

But this was the plan since begin 2016 and now in 2019 its still not done.

**Comment by viktorix** [comment]
Any update on this?

PHP can easily convert times based on timezones. If user is given dropdown of timezones to select, when appointment is registered app can simply convert the time into server's local timezone before sending anything to Google Calendar.

Simple example:
```
$date = date_create('2019-12-31 22:00:01', timezone_open('Europe/Amsterdam'));

// UTC
date_timezone_set($date, timezone_open('UTC'));
echo $date->format('Y-m-d H:i:s');
// 2019-12-31 20:00:01
```
Unless there's something more specific that I'm missing?

Was hoping to switch from Acuity Scheduling, which has timezone selection for customers:
https://help.acuityscheduling.com/hc/en-us/articles/218724808-Set-Your-Time-Zone

**Comment by alextselegidis** [comment]
@viktorix I know timezones is a very important feature, so I will add it to the v1.4 release. 

Follow progress here:
https://github.com/alextselegidis/easyappointments/issues/313

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
