### ISSUE TITLE
Error for refreshing Google calendar

### ISSUE THREAD

**Issue by AurelienC** [alextselegidis/easyappointments#449]
Hello,

I'm trying to install E!A V1.3.0 with my Google Calendar.

Synchronisation  **E!A --> Google** is OK.

But not working in the other wide (Google --> E!A). I have an error (*"Google synchronization failed: Could not establish server connection."*)

Into logds, I have this error :
`ERROR - 2018-03-19 16:12:03 --> Severity: error --> Exception: Call to a member function getDateTime() on null /home/www/rdv/application/controllers/Google.php 226`

Any idea ?

Thanks ! :-)

**Comment by alextselegidis** [comment]
Hi @AurelienC , 

sorry for the delayed reply, I checked the code and saw that the command fails: 

```
// Record doesn't exist in E!A, so add the event now.
                    $appointment = [
                        'start_datetime' => date('Y-m-d H:i:s', strtotime($event->start->getDateTime())), // --> this command fails
                        'end_datetime' => date('Y-m-d H:i:s', strtotime($event->end->getDateTime())),
                        'is_unavailable' => TRUE,
                        'notes' => $event->getSummary() . ' ' . $event->getDescription(),
```

That means that your calendar has entries that are not necessarily events. 

Can you please check on that and let me know what kind of entry fails so that I can integrate that in the syncing algorithm? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by AurelienC** [comment]
I didn't find any specific event. Now, the sync is done. Don't know why !

I have perform test with event, task, avalaible slot.

**Comment by alextselegidis** [comment]
Feel free to comment here once you have further info. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hi @AurelienC, thanks for the info. 

It seems that this is a custom event in your calendar that is not being taken care of during synchronization correctly. For example the event has no start and end time. 

Is this a full-day event? Maybe a reminder or similar?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by AurelienC** [comment]
Hi,

I don't find this event into my calendar. It seem be deleted.

Maybe, you could make an `if` on `statut`  do like this : `if (event.status!= "cancelled")` ?

**Comment by alextselegidis** [comment]
@AurelienC This might solve the issue but I guess I'll have to check again for edge cases in order to make sure we cover all possible scenarios. 

Anyway thanks for your help 👍  

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by quasipickle** [comment]
Sorry for necro-posting, but I am encountering this issue as well - on multiple calendars.  I'm not sure how to debug to the point of finding which entry is causing the issue.

**Comment by bevanjkay** [comment]
@quasipickle you could try changing line 222 of /application/controllers/google.php to this
`if ((count($results) == 0) && !is_null($event) && !is_null($event->start) && !is_null($event->end))`

This solved issues on my install.

**Comment by quasipickle** [comment]
@bevanjkay Thanks, that fixed my problem too.
@alextselegidis Will this fix be in a release soon?
