### ISSUE TITLE
Not getting the provider available hours  when making an appointment via backend

### ISSUE THREAD

**Issue by handoyo** [alextselegidis/easyappointments#450]
Hi, I found out that admins cannot get provider available hours when making an appointment. Is it made by purpose? If so, please consider to make the datetimepicker to show the provider available hours and date. Thanks.

**Comment by alextselegidis** [comment]
Hello @handoyo, 

you are right this is made on purpose. The reason is that admin users must be able to handle the schedule in any way they want without needing to search for available hours. 

If this is needed though, you'll have to use the booking page or you'll need to adjust the code in order to get this information in the backend calendar page.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
