### ISSUE TITLE
Not authorized to use the API.

### ISSUE THREAD

**Issue by bshiroya** [alextselegidis/easyappointments#465]
When i'm used rest api fetch data

Result is

You are not authorized to use the API.

**Comment by alextselegidis** [comment]
Are you referring to the JS fetch API? 

If so you'll need to provide the admin credentials with every call in order to authorize. 

https://stackoverflow.com/questions/43842793/basic-authentication-with-fetch

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bshiroya** [comment]
Yes I m using 
![screenshot from 2018-04-13 19-38-02](https://user-images.githubusercontent.com/7877551/38739347-4aa4041e-3f52-11e8-8c45-6525d2bd9769.png)
