### ISSUE TITLE
How to add available time slots

### ISSUE THREAD

**Issue by vishsid73** [alextselegidis/easyappointments#50]
HI,

If I add my google calendar, I would want to to have the already created event times to disappear or appear as booked. 
Currently, it does a overlap of event. If I have a 12.00 Noon meeting already setup in my google calendar than on the appointments page it should not list 12 noon to 1.00 pm slot.
 
If you could tell how to achieve it.

Siddharth

**Comment by alextselegidis** [comment]
I cannot reproduce. I suppose that you haven't synchronized Google with E!A yet. If you make changes in Google Calendar you will have to press the "Synchronize" button in the E!A backend in order to fetch the changes. Only Easy!Appointment changes are automatically synced with Google Calendar and not the other way around.
