### ISSUE TITLE
How to sync calendar events periodically

### ISSUE THREAD

**Issue by vishsid73** [alextselegidis/easyappointments#51]
HI,

I noticed that if a calendar event is being created directly, the event slot does not reflect automatically in the backend calendar view. It only appears after I press synchronize. and then only the unavailable slots appear in the appointment. Is there a way that appointment slots appear directly from google so to get updated result

Siddharth

**Comment by alextselegidis** [comment]
No there is no way unfortunately. Theoretically you can create a Cron job that will execute the "http://ea-installation/google/sync" URL but by default you have to be logged in and get a SESSION variable to execute this. 

One thing you can do is to comment lines 97 & 98 and add you secret token so that you authorize the call with that.  For Example:

Cron Job URL: "http://ea-installation/google/sync?token=23893094928347293874"

PHP Code: 

if ($_GET['token'] !== '23893094928347293874')
    throw new Exception('Invalid token provided');

// ... execute the synchronization
