### ISSUE TITLE
Show only one provider calendar

### ISSUE THREAD

**Issue by mediaclinic** [alextselegidis/easyappointments#516]
It would be great to have an option (URL?) tho show only one provider calendar so, that user can not change the calendar on drop down.

**Comment by alextselegidis** [comment]
Hello @mediaclinic, I would suggest that you create secretary users that are only assigned to a single provider and therefore cannot see the schedules of the other providers. 

Reaching backend pages always requires authentication and therefore a creation of a link is not needed since provider records can be assigned to secretaries. 

Thanks for posting! 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
You can provide URLs with preselected services and customers but currently Easy!Appointments ments to serve a single business and not multiple. 

That will need some code tweaking in order to work. This is a good place to start: https://www.codeigniter.com

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
