### ISSUE TITLE
Problem with mail sending

### ISSUE THREAD

**Issue by JeyJH** [alextselegidis/easyappointments#519]
Hello first of all I would like to thank you for all the work you have done.

I'm actualy encountering a problem with the mail sending function.
When I valid an appointment it register in the DB but doesn't send mail. 
Here is logs I get when i try to send a mail:
```
DEBUG - 2018-07-08 12:41:46 --> Config file loaded: /appointment/application/config/email.php
ERROR - 2018-07-08 12:41:46 --> EA\Engine\Types\Type: Invalid argument value provided (/appointments/index/0954733a7e831a5dd9cfd6cc5347be4d)
ERROR - 2018-07-08 12:41:46 --> #0 /appointment/application/controllers/Appointments.php(539): EA\Engine\Types\Type->__construct('/appointment/i...')
#1 /appointment/system/core/CodeIgniter.php(532): Appointments->ajax_register_appointment()
#2 /appointment/index.php(353): require_once('appointment/i...')
#3 {main}
```

Here is what my email config look like : 

```
$config['useragent'] = 'email@email.fr';
$config['protocol'] = 'smtp';
$config['mailtype'] = 'html';
$config['smtp_host'] = 'sslServer';
$config['smtp_user'] = 'email@email.fr'; 
$config['smtp_pass'] = 'emailPassword';
$config['smtp_crypto'] = 'ssl';
$config['smtp_port'] = portInNumber;

```

Thanks for help !

**Comment by iraudasoja** [comment]
I ended up to same kind of error. The appointment was saved but the confirmation email was not sent.

Problem is caused by the invalid urls generated if `BASE_URL` does not contains protocol (http or https).

I run my site on https protocol and keep it running, I have to set config variable `BASE_URL` as protocol relative url. Details [in this issue 235](https://github.com/alextselegidis/easyappointments/issues/235#issuecomment-259083556)

```
const BASE_URL              = '//<mydomain.com>';  // replace <mydomain.com> 
```

On `Appointments.php` line 539

```
$customer_link = new Url(site_url('appointments/index/' . $appointment['hash']));
``` 
My resolution was change this line and the next following line to use parameter `protocol` which is option to function `site_url`

My solution

```
$customer_link = new Url(site_url('appointments/index/' . $appointment['hash'], 'https:'));
$provider_link = new Url(site_url('backend/index/' . $appointment['hash'], 'https:'));
```

Hope this helps.

**Comment by JeyJH** [comment]
Thank you so much! 
It was a BASE_URL problem mine was 

`const BASE_URL              = '/websiteIndexFolder/appointments/'`


i replaced it to : 
` const BASE_URL              = 'https://mywebsite.com/websiteIndexFolder/appointments/'`

Didn't have to replace the 2 line in appointment.php 
Btw thank for help !
