### ISSUE TITLE
Error on setup: Cannot redeclare class SystemConfiguration

### ISSUE THREAD

**Issue by peterjohansen** [alextselegidis/easyappointments#52]
I get the following error after following all installation steps:
`Fatal error: Cannot redeclare class SystemConfiguration in /Applications/XAMPP/xamppfiles/htdocs/easyappointments/configuration.php on line 3`

I tried commenting out the class definition and setting each static variable manually (in *configuration.php*), like so:
`SystemConfiguration::$base_url = 'localhost/easyappointments/';`

This time I get an error message telling me that the class doesn't exist. What can I do?

**Comment by alextselegidis** [comment]
Try to install Easy!Appointments from the GitHub repository (v1.1 dev). You should not have this problem. 

Otherwise you need to search the project files and find where the configuration.php file is "required" from PHP. Find these places and replace with "require_once". Unfortunately I do not remember which sections they were cause its a long time this bug is fixed.
