### ISSUE TITLE
Select date before service worker

### ISSUE THREAD

**Issue by MihaiCraciun** [alextselegidis/easyappointments#525]
Hi,

First off, amazing plugin ! Really awesome and easy to use. 

I have a question regarding the configuration : in the front end is it possible to have the calendar date selection show up before having to select the service worker ?
I have a use case in which i have a **single location, single service and multiple service workers.** 
Right now i have to first select the service worker before being able to select an available time slot. 

What i would need is to first select a time slot and then the service worker list would only show available service workers for that date or a message if no available SW were found.

Is that possible through configuration ? 
If it can be done through custom code, could you give a brief description on how that can be achieved ?

Thanks so much!

**Comment by alextselegidis** [comment]
Hello @MihaiCraciun 

what you request can be done with code customizations, although it will require more server resources for the calculation of all the providers, upon date selection.

Basically you'll need to adjust the frontend files so that you switch the order of the booking steps. 

Then once the user selects the date you will make an AJAX request to a new endpoint (that needs to be created first) that will try to figure out which providers are available for the selected date and display them accordingly. 

Hope that helps

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
