### ISSUE TITLE
Specific user failing for Google Calendar Synchronisation.

### ISSUE THREAD

**Issue by bevanjkay** [alextselegidis/easyappointments#527]
All users on our domain seem to be working except for this specific user.
Is there a way to see which event is causing the error to throw?

`ERROR - 2018-07-24 14:53:03 --> Severity: error --> Exception: Call to a member function getDateTime() on null /home/gic/public_html/appointments/application/controllers/Google.php 220`

**Comment by alextselegidis** [comment]
Hello @bevanjkay, 

it seems to be that the syncronization get's stack on a certain event or data entry without dates, coming from Google Calendar. 

Can you confirm this? If yes can you share any additional information so that I can filter such entries out? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bevanjkay** [comment]
@alextselegidis 
Based on a suggestion in the Google group we added, 
`if ((count($results) == 0) && !is_null($event) && !is_null($event->start) && !is_null($event->end))` to line 116 and it is now working. I also had to force it to sync 60 days ahead as it seemed to only be checking 5 days in the future.

**Comment by Golyat0r** [comment]
I am haveing the same problem with version 1.3.1, 

Syncing from easy appointments calender to Google Calender works. Remvoing items from google calender is also synced to easy appointment. Setting up new items inside googlecalnder do not get synced into easy appointments calender. The google calnder it complety empty except 2 test entrances.

I get "Google synchronization failed: Could not establish server connection." and logs says "Severity: error --> Exception: Call to a member function getDateTime() on null /data/web/virtuals/234213/virtual/www/booking/application/controllers/Google.php 226"

i added if ((count($results) == 0) && !is_null($event) && !is_null($event->start) && !is_null($event->end)) to line 222 but still the same problem.

Any Idea what is wrong?

**Comment by Golyat0r** [comment]
I reseted my calender, but befor i printed what the syncer fetched and there were some entries which i deleted a long time ago and which were not even in the bin.
