### ISSUE TITLE
How to get the datepicker in wordpress in the right date format.

### ISSUE THREAD

**Issue by HettyvanH** [alextselegidis/easyappointments#529]
Hi! I'm new to Easy Appointments and like to use it on a WordPress website. I'm struggeling to get the datepicker in the right dateformat. What I need is d/m/y and the datepicker in the plugin shows m/d/y although I have the right settings in my wordpress settings.I use the latest version of Easy Appointments. I would be very happy if you could advise me on this.

Greetings, Hetty

**Comment by alextselegidis** [comment]
Hello @HettyvanH, 

since v1.3.1 you can select your own time format in backend settings page. 

You might need to update your existing Easy!Appointments installation so this might come in handy http://easyappointments.org/docs#1.3.1/update-guide.md

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
