### ISSUE TITLE
Can't remove (empty) customer notes field.

### ISSUE THREAD

**Issue by Jenot** [alextselegidis/easyappointments#541]
Can't delete customer notes (neither from Customers page nor edit appointment modal window on Calendar page). Changes are submitted only if number of characters >= 0 in notes field. No errors (standard info "Client has been saved" only). The only way to delete "notes" field is to leave at least one character. 1.3.2 version, standalone install on Ubuntu 16.04 or 18.04, Chrome or firefox web browser (Linux and MacOS).

**Comment by alextselegidis** [comment]
Hi @Jenot, that's indeed an issue based on a feature that was interoduced so that no customer information goes lost but we'll have to fix this. 

For now open the Customers_model.php file and check the update method and remove the following part: 

```  
        // Do not update empty string values.
        foreach ($customer as $key => $value)
        {
            if ($value === '')
            {
                unset($customer[$key]);
            }
        }
```

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
