### ISSUE TITLE
'ERROR  --> EA\Engine\Types\Type: Invalid argument value provided'

### ISSUE THREAD

**Issue by dele0017** [alextselegidis/easyappointments#544]
on version 1.3.2, we get the following message when we try to make a new appointment:
ERROR - 2018-09-18 12:09:41 --> EA\Engine\Types\Type: Invalid argument value provided (/rendezvous/index.php/appointments/index/9f198f5e801792dd501267ac0b5740ad)
ERROR - 2018-09-18 12:09:41 --> #0 /var/www/html/rendezvous/application/controllers/Appointments.php(562): EA\Engine\Types\Type->__construct('/rendezvous/ind...')
#1 /var/www/html/rendezvous/system/core/CodeIgniter.php(532): Appointments->ajax_register_appointment()
#2 /var/www/html/rendezvous/index.php(353): require_once('/var/www/html/r...')
#3 {main}

We don't receive any mail but no error is displayed in the application.

Any help would be welcomed.

**Comment by alextselegidis** [comment]
This is because your base url value is not a validate URL string. 

The type class will try to validate this but fail so that you get this error. 

Please use a URL that will pass the `filter_var($value, FILTER_VALIDATE_URL)` php validation. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
