### ISSUE TITLE
Add appointment edit link in the backend customers page.

### ISSUE THREAD

**Issue by Jenot** [alextselegidis/easyappointments#546]
Feature request: I nedd (my wife needs to be honest) additional functionality - editing appointments from customers page (i.e. click customer from list on the left, select appointment from the list and click edit button). For now editing appointment is possible from calendar view only. TIA.

**Comment by alextselegidis** [comment]
I'll be adding a direct appointment link in the customers page so that you can easily open the appointment handling modal in the calendar page. 

Direct edits in the customer page is kind of out of scope but I guess the link will do the trick. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
This feature got implemented for v1.4.0

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
