### ISSUE TITLE
Multi-Lang Front-End selection popup not working on Mobile

### ISSUE THREAD

**Issue by xcsn2005** [alextselegidis/easyappointments#550]
Version 3.3.5 of Bootstrap doesn't recognize touch events on modern displays for popups it creates. Thus, you cannot change language on mobile.

Also, Bootstrap >3.3.5 up to 4.0 has XSS security vulnerabilities due to use of "data-target" attribute in HTML code, see here : [SNYK Report](https://snyk.io/vuln/npm:bootstrap?lh=3.3.5)

I tried upgrading to latest Bootstrap 4.1.3 (which requires Popper.js), but it doesn't fit with Bootswatch Paper theme for Bootstrap 3.3.5 anymore, as the "Paper" theme has been deprecated in latest versions.

What to do?

**Comment by alextselegidis** [comment]
Hi @xcsn2010, I was planning to upgrade Bootstrap soon, as the new version works nicely. I'll mark this as a feature of 1.4.0 and try to integrate asap. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by yrammos** [comment]
@xcsn2005 if I understand correctly, a fix for this is included in my fork, [TekhneeAppointments](https://github.com/tekhneeappointments), where, additionally, the language selector is itself multilingual (displaying each option in the respective language) and supports language variants (e.g. British English). I haven't submitted a PR because the changes are invasive and, frankly, not as tidy as I'd like. But the particular issue you're describing *might* potentially be addressed by changing:

```css
li.language:hover {
	cursor: pointer;
    color: #005580;
}
```

to 

```css
li.language {
	cursor: pointer;
}

li.language:hover {
    color: #005580;
}
```

in `/src/assets/css/general.css`.
