### ISSUE TITLE
Front-End booking Calendar not syncing with Business Logic Working Plan

### ISSUE THREAD

**Issue by xcsn2005** [alextselegidis/easyappointments#551]
Even if the general Working Plan from back-end "Business Logic" tab includes all weekdays, in front-end booking calendar widget the weekend days are always grayed-out and clients cannot fix appointments during Saturday or Sunday.

**Comment by alextselegidis** [comment]
Hi @xcsn2010, this is because the providers still have their own working plan set and they weren't assign the new one. For now you will have to edit your provider records and click not he "Reset Working Plan" button to assign them the global working plan from the business logic tab. In the upcoming version there will be a button that will do exactly this thing automatically. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
