### ISSUE TITLE
Button 'Save' must be pressed twice in order for the New Appointment page to be closed(backend - v1.0.0)

### ISSUE THREAD

**Issue by lucianpp** [alextselegidis/easyappointments#57]
When creating a new appointment from backend, in order to save and close the page, button 'Save' must be pressed twice. Two appointments are inserted.
Pressing only once, the page does not close but we can close it with X and the one app is inserted in this case.

**Comment by alextselegidis** [comment]
I guess that when you press the button the AJAX request is executed and because it takes some time to be completed the user can press the button again...

The problem is that I cannot reproduce the problem because when I click the save button the loading spinner covers the entire screen and clicking any element is impossible (v1.1 dev).
