### ISSUE TITLE
Backend link in Footer going to `index.php/backend`

### ISSUE THREAD

**Issue by chrisspiegl** [alextselegidis/easyappointments#591]
Might just be cosmetic, but if redirection works properly the backend link should point to `/backend` instead of `/index.php/backend`.

**Comment by alextselegidis** [comment]
Hi @chrisspiegl, the first version of Easy!Appointments used to ship with such URLs. The problem was that many users couldn't get their servers configured correctly. Even with the provided .htaccess file there where issues and I had to change this back to the convention index.php URIs. 

You can still change the URLs as described here: 

https://stackoverflow.com/a/19197074

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by chrisspiegl** [comment]
Thank you @alextselegidis. I understand that and will potentially look into the redirect project.
