### ISSUE TITLE
Variable time slot selection

### ISSUE THREAD

**Issue by banstola** [alextselegidis/easyappointments#592]
Currently the time being booked is fixed. If customer wants to book a provider for a variable length of time, there should be possibility to do so.

**Comment by alextselegidis** [comment]
Hi @banstola, you mean like booking for e.g. 70 minutes, although the selected service duration is 30? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by banstola** [comment]
The use-case would be minimum booking time is 60 minutes for a task but customer has the possibility to book for as long as he/she wants  as long as the provider is available . E.g. I want to book a service provider from 15:12 to 21:37 

The provider is available from during that time and customer also wants to make the booking for that time

**Comment by alextselegidis** [comment]
Hi @banstola, I now understand you point better but find your use case too specific so that there is no quick solution/explanation for this feature. 

If you are feeling comfortable enough with conding, you can adjust the Appointments.php ajax_register_appointment method and dynamically change the end_datetime so that it fills the remaining available time of the provider.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by banstola** [comment]
> Hi @banstola, I now understand you point better but find your use case too specific so that there is no quick solution/explanation for this feature.
> 
> If you are feeling comfortable enough with conding, you can adjust the Appointments.php ajax_register_appointment method and dynamically change the end_datetime so that it fills the remaining available time of the provider.
> 
> ![](https://camo.githubusercontent.com/c099d8c84ee6739ccb2f789fc6c9310965553f53/687474703a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator 
>   [Need a customization? Contact me in person!](http://alextselegidis.com)

Thank you for guidance.

**Comment by idandylux** [comment]
Hello Alex,
we need also the possibility of choosing a flexible time slots. 15min 30min 45min 60min
That would be great for students to select flexible slots by my wife.
With this modification we could offer a great service to music students in Luxembourg. And we have nice chocolate here too ... ;) you know what i mean? :)
Andy and Paulina from Luxembourg
