### ISSUE TITLE
Correct .js and .css

### ISSUE THREAD

**Issue by gillesmich** [alextselegidis/easyappointments#593]
Jacob Andrew
Can you provide please the correct .js and .css
Thanks a lot in advance

**Comment by alextselegidis** [comment]
Hi @gillesmich, I'm sorry I do not understand your inquiry. 

Can you please elaborate? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by gillesmich** [comment]
Hi Alex ,There is a ajax error with the current version on tablets and smartphone.According to the discussion on the web, it should be caused by a wrong .js ( front_booking_api.js and front.css , -the nouns are about like that- )Kind RegardsGillesLe 8 févr. 2019 09:05, Alex Tselegidis <notifications@github.com> a écrit :Hi @gillesmich, I'm sorry I do not understand your inquiry.

Can you please elaborate?



  Alex Tselegidis, Easy!Appointments Creator 

  Need a customization? Contact me in person!

**Comment by gillesmich** [comment]
Cfhttps://github.com/alextselegidis/easyappointments/issues/305Le 8 févr. 2019 11:26, Gilles <gillesmich@yahoo.fr> a écrit :Hi Alex ,There is a ajax error with the current version on tablets and smartphone.According to the discussion on the web, it should be caused by a wrong .js ( front_booking_api.js and front.css , -the nouns are about like that- )Kind RegardsGillesLe 8 févr. 2019 09:05, Alex Tselegidis <notifications@github.com> a écrit :Hi @gillesmich, I'm sorry I do not understand your inquiry.

Can you please elaborate?



  Alex Tselegidis, Easy!Appointments Creator 

  Need a customization? Contact me in person!

**Comment by gillesmich** [comment]
frontend_book_api.jsLe 8 févr. 2019 11:31, Gilles <gillesmich@yahoo.fr> a écrit :Cfhttps://github.com/alextselegidis/easyappointments/issues/305Le 8 févr. 2019 11:26, Gilles <gillesmich@yahoo.fr> a écrit :Hi Alex ,There is a ajax error with the current version on tablets and smartphone.According to the discussion on the web, it should be caused by a wrong .js ( front_booking_api.js and front.css , -the nouns are about like that- )Kind RegardsGillesLe 8 févr. 2019 09:05, Alex Tselegidis <notifications@github.com> a écrit :Hi @gillesmich, I'm sorry I do not understand your inquiry.

Can you please elaborate?



  Alex Tselegidis, Easy!Appointments Creator 

  Need a customization? Contact me in person!

**Comment by alextselegidis** [comment]
Thanks for the feedback, if this is an AJAX error then the problem is more likely to be in the server returning an error and not the js. 

Do you have a live installation where I can check this? 

Also which devices are you using for testing?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by DE10011001** [comment]
you may check this issue also here: https://schweizerklimaanlagen.ch/easy!app
I tried iPhone 8, Safari on Mac, SG2, and had AJAX ERROR:.
Or Safari on Mac `[Error] Origin http://schweizerklimaanlagen.ch is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://schweizerklimaanlagen.ch/easy!app/index.php/appointments/ajax_get_unavailable_dates?provider_id=2&service_id=1&selected_date=2019-02-18&csrfToken=1e7fa16ec00be5110bacbf513fa8f7f4&manage_mode=false due to access control checks.
[Error] Failed to load resource: Origin http://schweizerklimaanlagen.ch is not allowed by Access-Control-Allow-Origin. (ajax_get_unavailable_dates, line 0)`

**Comment by gillesmich** [comment]
HelloPrecisely, there is an error Ajax on smartphone Android and maybe also Ios, which prevents to select hours. Kind regards, Le 18 févr. 2019 18:42, "formdesign.ch" <notifications@github.com> a écrit :you may check this issue also here: https://schweizerklimaanlagen.ch/easy!app
I tried iPhone 8, Safari on Mac, SG2, and had AJAX ERROR:.
Or Safari on Mac [Error] Origin http://schweizerklimaanlagen.ch is not allowed by Access-Control-Allow-Origin. [Error] XMLHttpRequest cannot load https://schweizerklimaanlagen.ch/easy!app/index.php/appointments/ajax_get_unavailable_dates?provider_id=2&service_id=1&selected_date=2019-02-18&csrfToken=1e7fa16ec00be5110bacbf513fa8f7f4&manage_mode=false due to access control checks. [Error] Failed to load resource: Origin http://schweizerklimaanlagen.ch is not allowed by Access-Control-Allow-Origin. (ajax_get_unavailable_dates, line 0)

**Comment by DE10011001** [comment]
mysql, PHP, Apache Version  10.1.38 Maria DB, 5.6.40, 2.4.37
Depend the .htaccess settings and the config.php, when config.php BASE_URL not SSL, no error anymore showing.

**Comment by alextselegidis** [comment]
This is a server configuration issue. 

Calling this URL http://schweizerklimaanlagen.ch/easy!app/ I have no problems, meaning that all requests should aim to HTTPS. 

You can do this by enabling automatic redirection to HTTPS for your server. 

Another possible way would be to omit the HTTP protocol in the BASE_URL of the config.php but I'm not sure if that will work in all cases to be honest. 

You could try it like this: 

BASE_URL = '//schweizerklimaanlagen.ch/easy!app'

Would be great to know if this works for you without problems :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
