### ISSUE TITLE
New calendar events not refreshing in front end

### ISSUE THREAD

**Issue by aptonline** [alextselegidis/easyappointments#618]
Upon adding new new events in the backend these are not automatically appearing in the front end leading to ‘unexpected issues’ when users try a book a date/time that is not available.

The work around seems to be to have to manually reload in the backend prior to logging off but this doesn’t seem to be persistent as even when logging into the back back to not make any changes the front end seems to not display the correct availability.

It’s also allowing me to attempt to book events when the slots are already used. I have a single provider with multiple services in a few categories.

Can this be investigated?

**Comment by aptonline** [comment]
![1169709A-2613-4E2B-AA90-8200C68474B1](https://user-images.githubusercontent.com/190136/57703730-8e69aa80-7658-11e9-8242-4f8e2095ae0f.jpeg)

This appears when users attempt to book when a slot is already filled. Slots are displaying even when already filled.

**Comment by yrammos** [comment]
Wouldn't this be wonderfully solved with a new REST URI, for example `http://ea-installation/index.php/api/v1/sync`?

Alternatively, I suppose, a cron job running every minute would work well, if there was a command-line facility on the server side to trigger the sync, such as:

`php ./easyappointments sync`

**Comment by alextselegidis** [comment]
Hello! 

This issue has been fixed in v1.4.0, please update your installation.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
