### ISSUE TITLE
can't install, it asks for an index file that doesn't excist

### ISSUE THREAD

**Issue by leeuwtjex** [alextselegidis/easyappointments#624]
Hi team,

Probably a beginners question. I don't understand the working of the app.
When I setup the app on my webserver (wamp for local testing) 
and config the config.php file. This is the result in the browser:

Not Found
The requested URL /easyappointments/index.php/installation/index was not found on this server.

It seems to refer to a file that is simply not there.: /easyappointments/index.php

Following the user manual, it seems to need a "installation folder" in the root of the application folder, but it isn't there. I just did a ordinary git clone to download the whole structure to my webserver root. 
Also I don't see it in the list here on github....

What is it I don't understand?

**Comment by alextselegidis** [comment]
@leeuwtjex The installation guide https://easyappointments.org/docs.html#1.3.2/installation-guide.md will help you through the correct installation of the app. 

There are also some videos on how to perform a new installation from scratch. 
https://www.youtube.com/watch?v=1JqIXr6Z1Ow

The app will try to redirect you to the installations page the first time you open it from your browser. 

Since the page is not found there are two cases: 

* Either the BASE_URL of your config file is wrong

* Your webserver cannot properly resolve urls like index.php/path/info/after/file

Hope this helps :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
