### ISSUE TITLE
ajax_get_unavailable_dates error

### ISSUE THREAD

**Issue by luisdias** [alextselegidis/easyappointments#626]
Hi. 
Thank you for this great software.
I am getting an error while booking. 
the ajax_get_unavailable_dates gives an error 
"Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in ..."
I tried to increase PHP.ini memory_limit but it does not fixed. 
Neither max_execution_time.
If I delete some of the last records inserted in the ea_appointments table, the site works again.
The site worked during almost 2 years without any problem.
Help me!

**Comment by alextselegidis** [comment]
@luisdias IS this still an issue? I don't think this is a problem, it seems more like an ever ending loop due to unknown conditions. 

Please provide more information on your calendar state, number of events and their duration. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by luisdias** [comment]
Exactly! It is  an ever ending loop due to unknown conditions. The site user stopped using the backoffice and no errors ocurred. Is it possible to be a browser specific issue? There are 1578 records on the ea_appointments table. The basic duration of the events is 180 minutes.

**Comment by alextselegidis** [comment]
This is not a browser specific issue, it is the server that has the problem. 

It can be that there's also a memory leak that can be reproduced with many appointments. 

I will to some check based on your provided data and see if I can reproduce. 

In the meanwhile if any other user has the same problem, it would be interesting to know more information about your environments. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Could not find any related problem. I will close the ticket for now but will come back in case this happens again.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jamesgrogantech** [comment]
Hi, I'm having exactly this problem. System has been deployed for months now but suddenly has started to cause problems despite nothing being changed. I haven't tried to remove records on the appointments table as this is a live system. I set it to debugging mode in config.php. Upon entering the book appointment side it throws this error:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/u464234733/domains/tashthebarberstop.co.uk/public_html/book/application/controllers/Appointments.php on line 935
> 
> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 28672 bytes) in /home/u464234733/domains/tashthebarberstop.co.uk/public_html/book/system/core/Exceptions.php on line 37

I have had a look at the referenced lines of code but it doesnt really explain a lot about what is causing it. 

The server is running PHP 7.2 
I'm confused as to what might be causing this to happen as the system hasn't been touched since it's deployement.

I would be very grateful if anyone could suggest ways I could solve this. 

Thanks,
James

**Comment by alextselegidis** [comment]
Hello! 

Can you please check your entries in the appointments and see if you have any where the start date time is later than the end datetime? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jamesgrogantech** [comment]
> Hello!
> 
> Can you please check your entries in the appointments and see if you have any where the start date time is later than the end datetime?
> 
> ![](https://camo.githubusercontent.com/8cff9d0a6daf9fd5c73786aa4e74f327b5a5ac9b/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Contact me in person!](https://alextselegidis.com)

Just queried the database and found two appointments which had start dates after the end dates. Deleted these entrys and it has resolved the issue for now at least. Just wondering why this was able to happen in the first place. 

Regardless, thank you very much!

**Comment by alextselegidis** [comment]
Great, so this is something that is resolved in v1.4.0. 

Now there must have been some invalid data entry that passed through the validation. 

But this won't be happening any more with the new release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
