### ISSUE TITLE
Insert new appointment by clicking directly on the calendar.

### ISSUE THREAD

**Issue by surching4u** [alextselegidis/easyappointments#65]
Hi,
"Easy appointment" should let user add appointment easily. Adding appointment is very tedious selecting hour and minutes. And both field title is Start Data/Time.

It will be easy if one could click on grid and get selected Date/Time and Provider. No service should appear by default (Chance of making mistake). Let user select service. Instead of selecting end time it will be better to put duration.

e.g.

Provider : [selected provider]
Service  : Choose service
Date/Time : [selected date/time by clicking on grid]
Duration : 20 min (Let user change min value)

Thanks
Vicky

**Comment by alextselegidis** [comment]
Hello, 

I guess you mean the backend/calendar appointment creation, because for the frontend there is the booking wizard. 

The thing is that in backend the admin is capable of changing all the appointment details (even the end time) while he can select someone of the registered customers. There is a ticket already for the automatic end time calculation and this will be implemented for v1.1. 

The rest of your request seem to be good hints so I will leave this issue open for implementation in the next version v1.2.

Thanks for noticing, 

Alex

**Comment by dalamberts** [comment]
Hi, I am needing this feature right away.  Can you provide me some guidance of how to capture the date and time from the click in jQuery?  Or even some explanation of the various table layouts so I can use the various traverse functions to find this information?  Any help that you may provide will be appreciated!

**Comment by pavchonator** [comment]
SliderAccess integration would e nice
