### ISSUE TITLE
Can't Sync with Google Calendar

### ISSUE THREAD

**Issue by eleyth** [alextselegidis/easyappointments#665]
Hello, i install plugin and configure as you mention in documentation, but when i click on backend the sync button with google calendar, it keeps loading and loading and nevers syncs.

**Comment by alextselegidis** [comment]
@eleyth, there's probably an error happening during the syncing. 

Can you check on the logs or at the browser dev tools for additional information and post them here? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closed due to inactivity

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
