### ISSUE TITLE
provide ical file or export option for calendars

### ISSUE THREAD

**Issue by lachlan-00** [alextselegidis/easyappointments#67]
I have no idea how to set up the google sync there doesn't seem to be any user option to enable this?

How about just an ical or something i can import instead?

**Comment by alextselegidis** [comment]
Hi there, checkout this configuration guide for Google Calendar. 

There is no support for iCal yet ...

**Comment by JMCA2** [comment]
@alextselegidis Any plans to offer iCal support? So that you can subscribe to the calendar from any service, including Outlook.com and not only Google Calendar

**Comment by alextselegidis** [comment]
Hi @JMCA2, in the upcoming release I will integrate ICS files for each event in that so that they can be imported into other systems that support this format. 

There was also a feature request for CalDAV support but this will be implemented at a later point. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by samtuke** [comment]
+1 For ical and caldav support

**Comment by joshp23** [comment]
Great app, I agree, calDAV would be excellent.
