### ISSUE TITLE
Can't install! invalid timestamp field

### ISSUE THREAD

**Issue by sprppo** [alextselegidis/easyappointments#685]
Servidor: Localhost via UNIX socket
    Tipo de servidor: MySQL
    Conexión del servidor: No se está utilizando SSL Documentación
    Versión del servidor: 5.5.62-cll - MySQL Community Server (GPL)
    Versión del protocolo: 10
    Usuario: cpses_fc6kg8207y@localhost
    Conjunto de caracteres del servidor: UTF-8 Unicode (utf8)

Installing version 1.3.2

it says

Ha ocurrido un error con la base de datos
		Error Number: 1067Invalid default value for 'created'

CREATE TABLE IF NOT EXISTS `ea_consents` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME DEFAULT CURRENT_TIMESTAMP

meaning I can't have two fields with default current_timestamp. I am supposed to have a newer version of PHP, it should run. I've seen other users facing the same problem, none of them found a solution; perhaps you can help!

Thank you in advance!

**Comment by alextselegidis** [comment]
Hi @sprppo 

please update your mysql version as there's an incompatibility withe versions below v5.6

This will be fixed with the coming release v1.4 of Easy!Appointments but for now I would advise to update. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
