### ISSUE TITLE
Feature-Request : user login for managing appointment

### ISSUE THREAD

**Issue by poulpator** [alextselegidis/easyappointments#69]
Hi, 
First :  thanks a lot for your work !!!
Second, do you think  we can add a  private area for user manage themself their  appointments with a third party like "http://phpauth.github.io/PHPAuth/" ?

Best regards from French alps ;-)
Emmanuel.

**Comment by alextselegidis** [comment]
Hello 

Currently the database structure allows customers to have their own credentials and it is possible to easily create a management page where they can see their appointments. 

You can do this by using the "ea_user_settings" table which is where settings about E!A users are stored. 

I would also recommend you to learn the CodeIgniter framework because it is used for the implementation of the application.

Best regards,

Alex
