### ISSUE TITLE
Check whether the provider is still available in the selected appointment date. Not working correctly.

### ISSUE THREAD

**Issue by lao9s** [alextselegidis/easyappointments#691]
The function `checkDatetimeAvailability()` from **Appointments.php** not working correctly. This does not check past hours.

I think for this function is more efficient to call `getAvailableHours` and check if selected time is in array or check if selected time is `<=` that others hours from array.

**Comment by alextselegidis** [comment]
Hello @lao9s,

thanks for posting! Since the system will only display availability hours for the future, why do you think the checkDatetimeAvailability method must check past hours? 

Can you please elaborate on this? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by lao9s** [comment]
HI @alextselegidis,
Because somebody may can to register new appoinment with past hours. Example: The  user leaves open the confirm page in browser for 1 hours, after 1 hour when he will confirmed appoinment we need to check if the date selected is not past and if is in array of available hours.

**Comment by alextselegidis** [comment]
Hello! 

These problems are fixed and updated in the new v1.4.0 version

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
