### ISSUE TITLE
First API Request

### ISSUE THREAD

**Issue by matheuscmacedo0** [alextselegidis/easyappointments#703]
Hi.
I'm getting started and i need some help to do my first API request.

I've recently installed Easy Appointments on my server and followed the steps shown on the documentation, but couldn't make it work. 
First created an account and registered some appointments.
Then i tried to do the request using curl:

curl http://mhais.com.br/index.php/api/v1/appointments --user myuser:mypassword

Got this error message
*******************************************************
Invoke-WebRequest : Unable to find a positional parameter that accepts the '--user' argument.
No linha:1 caractere:1
+ curl http://mhais.com.br/agendamento/index.php/api/v1/appointments -- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
******************************************************
I also tried using Postman, but got the "You are not authorized to use the API." error message.

**Comment by popod** [comment]
Are your on Windows ? If yes, this could be [this error](https://stackoverflow.com/a/30794808/8697449).

**Comment by alextselegidis** [comment]
Hello! 

Although this is an older issue, this might be helpful for new user errors. 

If you are providing the right credentials but you still get the "You are not authorized to use the API."  error, that means that your server will not pass the `Authorization` header to PHP. 

This is a problem because the app will not be able to auth the user correctly. 

For that (as noted in the REST API doc), you will need to configure your server as follows: 

### Authorization Issues

If your server runs PHP through FastCGI you will the authorization will not work because the `Authorization` header is not available to the PHP scripts. You can easily fix this by applying the following adjustments depending your server software: 

### Apache

Add the following code snippet to an `.htaccess` file in the installation root directory if you have `mod_rewrite` installed and enabled: 

```
RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```

[[Source]](http://stackoverflow.com/a/22554102/1718162)

Add the following code snippet to an `.htaccess` file in the installation root directory if you have `mod_setenvif` installed and enabled: 

```
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
```

[[Source]](http://stackoverflow.com/a/27229807/1718162)

### NGINX

Add the following code snippet to the NGINX `.conf` file: 

```
fastcgi_param PHP_AUTH_USER $remote_user;
fastcgi_param PHP_AUTH_PW $http_authorization;
```

[[Source]](http://serverfault.com/a/520943)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
