### ISSUE TITLE
Customer data is overridden

### ISSUE THREAD

**Issue by Elvin-Xhimitiku** [alextselegidis/easyappointments#721]
Hello

while testing out for a use case, I noticed the following problem:

If either the same user, or 2 different people, use the same email address (maybe a mistake by them), the user data gets overridden.

TEST:
Make first appointment:
Fist name: JOHN
Last name: DOE
email: johndoe@example.com

Make second appointment:
Fist name: SAM
Last name: SMITH
email: johndoe@example.com

- now when you check for the customer, you don't have 2 customers with the same email, but only the last customer data.

see attached also. i filled the first application with another name, did the second with ENDRI ENDRI and now its only retaining the last submission data.

![Screenshot 2020-04-02 at 8 19 32 PM](https://user-images.githubusercontent.com/841806/78284197-55ac1b80-751f-11ea-8b98-162d8580dabd.png)

**Comment by ac1234** [comment]
I can confirm the same behaviour, couldn't work out what was happening but it does seem to be over writing the database not inserting new account. Version 1.3.2

**Comment by alextselegidis** [comment]
Easy!Appointments uses the customer email as an ID and it will try to update changed data if there are some. 

In the future possibility for guest appointments will be added, so that customers are not overwritten but duplicated. 

Nevertheless, this behavior can be changed on demand for your own installation. Consider booking the Customization Service: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
