### ISSUE TITLE
ajax_get_available_hours error

### ISSUE THREAD

**Issue by Demilancer6** [alextselegidis/easyappointments#732]
Hi, last weekend I installed the plugin on a localhost server. After a few hours of figuring out how to install it, I found no issues once installed. Yesterday I bought a domain and hosting, so I am now trying to install the plugin on my new site. However, I keep encountering an error while trying to access the plugin from my website. 

At first, it gave me some 'AJAX error', which in 'view source mode' appeared to be some problem with a CORS policy. I Googled how to solve it. Now it doesn't show that CORS policy error anymore, but instead it gives a 403 error when trying to load the 'https://[domainname]/easyappointments/index.php/appointments/ajax get available hours'
(see images for screenshots of both errors)

And I cannot figure out how to solve this.

Thanks in advance

![CORS error](https://user-images.githubusercontent.com/64539394/80604155-a6853600-8a31-11ea-9781-463d18510bfe.png)

![http 403 error](https://user-images.githubusercontent.com/64539394/80604007-72aa1080-8a31-11ea-9d34-554310626135.png)

**Comment by alextselegidis** [comment]
Hello @Demilancer6 

The server sends a `403 Forbidden` error back. 

I cannot tell why this is happening but it seems that this is a configuration problem. 

Unfortunately I cannot help further. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by llwp** [comment]
For any intrepid Google Searchers like myself ...

I was encountering this as well due to CORS setup, originating from the CodeIgnitor framework Security.php and potentially related to the Easy!Appointments domain configuration where only 1 domain is defined.  I discovered a very specific endpoint as the cause ...

From `csrf_set_cookie` I found that the array `csrf_exclude_uris` needed a small modification ... the CSRF are features added to the framework and it does allow for exclusion of URIs from the CSRF protection if needed.  For me, the URI culprit was `appointments/ajax_get_available_hours` such that even though the domain/server was permitted in other configuration, there was still a failure (403) calling that specific endpoint as it is not in the predefined permissive `api/vN` path.  A long term fix might be moving the endpoint.  However, simply adding the needed path to the URIs serves for the time being as a workaround.  Adding it here is the workaround I used: `application/config/config.php#L387`

New line:
```
$config['csrf_exclude_uris'] = ['appointments/ajax_get_available_hours'];
```

**Comment by ronvanderzwan** [comment]
Thanks for the workaround, I had the same issue using iframes. This fixed it.

**Comment by skylarmt** [comment]
I ran into the same issue, but the same problem happened when confirming the appointment.  I modified this:

```php
$config['csrf_exclude_uris'] = ['api/v1/.*'];
```
to this:

```php
$config['csrf_exclude_uris'] = ['api/v1/.*', 'appointments/ajax_.*'];
```

Now the special API the appointment wizard uses is completely excluded.

Bonus: to make it appear more seamless in my website, I also added this CSS:

```css
#header {
        display: none;
}

#frame-footer {
        display: none;
}

.frame-title {
        display: none;
}

html,body,#book-appointment-wizard {
        background: none transparent;
        box-shadow: none;
}
```
