### ISSUE TITLE
Adding field in email

### ISSUE THREAD

**Issue by aleccf0** [alextselegidis/easyappointments#766]
Can the "notes" field be sent in the Notification Email?

I am only getting Name, email address, phone number and customer address.
I need to add the "notes" which is a field already present at booking time

Thanks in advance

**Comment by alextselegidis** [comment]
Hello @aleccf0 

In the future I plan on adding a template editor to the app so that you can change the message layout and contents.

For now this will not be implemented because we try to keep the email as compact as possible. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by PierfrancescoElia** [comment]
Hi, I need the Notes filed on the e-mail.
Unfortunately, writing _$customer_notes_ is not enough to display the notes (ehehe).

I gently ask you what PHP file is handling the appointment_details.php file in the views/email folder in order to make it work.

Thanks a lot!
