### ISSUE TITLE
Individualized response emails with meeting location per service

### ISSUE THREAD

**Issue by zamansky** [alextselegidis/easyappointments#788]
It would be great if one could specify the information to go in the confirmation email when one makes an appointment on a per session basis. For example, a phone number, address, zoom link etc. 

I'd like to try to add this feature (have forked and read the contribution guidelines) but don't know if I'll  get it done as I'm an absolute beginner with PhP and haven't touched MySQL in over a decade.

**Comment by alextselegidis** [comment]
Hello @zamansky 

In the future I will add a email template editor so that you can change the contents of the notifications.

For now you will need to change the code for this to work. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
