### ISSUE TITLE
Make customer email a nonrequired field

### ISSUE THREAD

**Issue by Answerx32** [alextselegidis/easyappointments#790]
Hello,
I am trying to make the customer email an unrequired field when I create a new appointment, but I get the folowing unexpected warning: EA\Engine\Types\Type: Invalid argument value provided (). It happens when I press the save button or when I delete an appointment.
Can someone help me please?

**Comment by fanonym** [comment]
I agree and support. At least so the email can be repeated. It would be best to put this required email option in the application settings.

**Comment by vixper** [comment]
Hi, I'm interested in this feature too, a lot of clients (in my case) doesn't have an email address

**Comment by wvdvegt** [comment]
Same here, furthermore, asking emails is a privacy issue often as you start collecting personal data.

**Comment by nottheend** [comment]
agree, would be really nice if mail address is required or not would be configurable if

other than that really nice though

**Comment by alextselegidis** [comment]
Hello! 

The email field is needed for many standard operations so that it cannot be removed just like that. 

In the future we will have guest and registered user appointments where we could make emails optional. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
