### ISSUE TITLE
Customers list [beckend section]

### ISSUE THREAD

**Issue by Picazz** [alextselegidis/easyappointments#799]
at backend section  if customer list more than a N * thousand records then its take a long time for loading(AJAX) , and sometimes this request could throw callback with message "AJAX ERROR" 
It will be much better to set limits for customer list on first empty filter request with ordering by appointment registration datetime (or ID) **DESC**. and add script for on scroll event to send request for the next pull of customers. 
`
$("div#filter-customers div.results").scroll(function(){
	$.post(......)
}
`
![image](https://user-images.githubusercontent.com/18707182/83626488-29079500-a59e-11ea-8f63-d20418db154b.png)

**Comment by makayabou** [comment]
Please change title from [beckend section] to [backend section].

**Comment by alextselegidis** [comment]
Hello!

This is fixed with v1.4.0, as there's now pagination in all backend pages. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Picazz** [comment]
> Please change title from [beckend section] to [backend section].

done
