### ISSUE TITLE
Unregistered creation of appointment can lead to DOS of the service

### ISSUE THREAD

**Issue by Areizen** [alextselegidis/easyappointments#801]
Hi,

By intercepting the request of creation of an appointment from a non authenticated user and modifying the duration of this appointment to a negative value we make the server crash at each try of appointment creation, so no more user can create an appointment.

**Step to reproduce**
- Create an appointment
- Intercept the request with a proxy ( Burpsuite, Mitmproxy, ...)
- Change the starttime and the endtime so the appointment have a negative duration
- Send the request

Now it's impossible to create any more appointment.

**Fix**
To fix this problem, check the appointment duration server-side.

Have a good day

**Comment by alextselegidis** [comment]
Hello!

Thanks for posting this. 

Since v1.4.0, Easy!Appointments will validate the appointment duration and actually make sure it is no less than 5 minutes. 


<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
