### ISSUE TITLE
email confirm request

### ISSUE THREAD

**Issue by mbaldazzi85** [alextselegidis/easyappointments#814]
Is there a registration confirm to verify the email field?
if not could it be a "pull request" for improvement to avoid spam?

**Comment by alextselegidis** [comment]
Hello! 

I'm not sure that I understand your question/proposal correctly. 

Can you please elaborate? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mbaldazzi85** [comment]
before finishing the creation of the appointment if possible put a verification email on the email you intend to register?

**Comment by alextselegidis** [comment]
Ah I see, well since in the future there will be a way for customers to register or optionally book as guest, the registration step will cover this need. We can therefore close the ticket and wait till the customer registration system is ready. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mbaldazzi85** [comment]
Ok thanks. What is the release date of new version?

**Comment by alextselegidis** [comment]
In a couple of days there'll be an alpha version released. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
