### ISSUE TITLE
Issue Building Server Dockerfile

### ISSUE THREAD

**Issue by Elte156** [alextselegidis/easyappointments#819]
https://github.com/alextselegidis/easyappointments/blob/e857d3a37e62a33f9e048a8b47bea17852147479/docker/server/Dockerfile#L14-L15

```console
Step 5/6 : RUN pecl install xdebug     && docker-php-ext-enable xdebug
 ---> Running in 32da1667d848
No releases available for package "pecl.php.net/xdebug"
install failed
ERROR: Service 'server' failed to build: The command '/bin/sh -c pecl install xdebug     && docker-php-ext-enable xdebug' returned a non-zero code: 1
```

**Comment by OscarKolsrud** [comment]
If i am not mistaken you can simply remove line 14 and 15. This extension is used for debugging

**Comment by alextselegidis** [comment]
Hello!

I tried to build again the docker environment of the develop branch and couldn't reproduce the problem. 

@OscarKolsrud is right though, xdebug is only needed for debugging session and can be considered as optional. 

Not sure if the error could be due to some local environment setting but we will definitely need more information. 

There is also documentation about the Easy!Appointments Docker setup in the `docs` directory.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
