### ISSUE TITLE
Add optional (configurable with setting) phone number validation.

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#820]
For now, no validation is done for the phone number.
Adding some validation would be great.

**Comment by alextselegidis** [comment]
Hello! 

That would be a nice thing, however phone numbers may differ from country to country. 

PHP also does not have a baked in method to validate such values which means that we will need to go for an arbitrary solution. 

I will skip this for now as I do not want that this potentially becomes a problem any user. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
Hi,

Yes, phone number validation is very difficult.. But what about a "soft validation" ? Because, for now customers can enter "abc" in the phone number field..

For example, libphonenumber from google has a [PHP implementation](https://github.com/giggsey/libphonenumber-for-php) which allow to "soft validate" phone numbers.
"
An other solution will be to only allow numbers in the phone number field or a pattern like "+xxxxx" (where "x" is a number and could have a length from 5 to 20 for exemple which I think cover all "normal" phone numbers in the world). And this validation could be enabled/disabled with a settings option.

What do you think about that ? This is a complicated think, but I think that improve this validation will be a good thing to do :)

**Comment by alextselegidis** [comment]
Soft validation might actually be a good option indeed so that the app does not allow invalid data to be entered. This will also have to be implemented in the frontend so that users see something like a mask when entering data. 

I will re-open the ticket and set it for v1.5.0. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jasimp** [comment]
Is is possible to implemented similar to gravity forms

[https://docs.gravityforms.com/gform_phone_formats/](url)

**Comment by rimas-kudelis** [comment]
@alextselegidis, this doesn't seem to work in develop branch. Was this removed at a later point?

I'm currently in the process of implementing backend phone number validation using the library suggested by @popod. Would you be interested in a PR?

**Comment by alextselegidis** [comment]
Back when I worked on this I decided to always run the validation, because entering alphanumeric values to the phone number would never be a good idea. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rimas-kudelis** [comment]
Yeah, I noticed that it actually works, but is just very very lax.
My PR above improves frontend validation (keeps yours as fallback in case the required library is unavailable) and adds backend validation during customer submission.

**Comment by alextselegidis** [comment]
Right, there were some users that did not want the strict validation, so toggling this with the setting will work for all cases. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
