### ISSUE TITLE
ea_appointments table has no data when booked

### ISSUE THREAD

**Issue by carmelnguyetmy** [alextselegidis/easyappointments#827]
Hi everyone! I need help .When the customers booked!  the information data does not have in ea_appointments table. it was saved in ea_user!? someone help me the reason why and how to fix it. thanks all!!!

**Comment by alextselegidis** [comment]
Hello @carmelnguyetmy! 

It is by design so, that users are common within the system so that further handling can be done. 

For example there are numerous instances out there that share their customers base with third party services in order to achieve powerful integrations. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
