### ISSUE TITLE
Dev blows up when *optional* settings are not configured

### ISSUE THREAD

**Issue by hopeseekr** [alextselegidis/easyappointments#83]
The reason is that 

`throw new Exception('$name setting does not exist in database : ' . $name);`

in settings_model.php is not caught by the front page controller. The entire user-facing frontend then fails to load. This is **hell** on development boxes, where Google Analytics **cannot** and **should not* be configured.

Right now, I just comment out the exception, but that is surely not a fix!

If you want to address this issue, please notify me in the comments so we aren't duplicating efforts! 

Also, I would **Love** to see your Feature roadmap and see if there is anything I can help you with!

I will probably address this issue in 24-36+ hours, if you have not notified me.

Also, damn github doesn't have IM, but my skype ID is public enough: php.pro, if you want to shout out.

**Comment by alextselegidis** [comment]
Normally you should not get this error because the "google_analytics_code" setting will be created by the updater. I suppose that it is missing from your installation so you can either execute the update operation or added manually to the ea_settings table. 

INSERT INTO ea_settings (name, value) VALUES("google_analytics_code", "");

**Comment by hopeseekr** [comment]
Um, this should be re-opened then, because it certainly isn't setting that field via the installer...
