### ISSUE TITLE
[Docker] [develop] Warning: require_once(/var/www/html/vendor/autoload.php

### ISSUE THREAD

**Issue by StarWhiz** [alextselegidis/easyappointments#844]
In order to solve #754 I removed old containers and deleted the master branch folders. Then I pulled the develop branch and did a `docker-compose up -d --build`

However after it was built I got the same errors as @FacundoAcevedo and @makayabou. Here is the screenshot below. Is there anyway I can solve this?

![image](https://user-images.githubusercontent.com/9423276/87073938-038c2d80-c1d3-11ea-9df9-9b44d5d20349.png)

**Comment by alextselegidis** [comment]
Hello @StarWhiz 

You will need to perform a `composer install` command before using docker, to make sure the vendor files are downloaded.

**Comment by StarWhiz** [comment]
I got past it but now I have an issue logging in to the backend section.

"Cookie “csrfCookie” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite"

Any ideas?

![image](https://user-images.githubusercontent.com/9423276/89589806-486baa00-d7fb-11ea-861e-d3d373d2f4e4.png)

**Comment by abdennour** [comment]
getting same issue
![image](https://user-images.githubusercontent.com/1788384/128422213-bc3c17e6-8935-49c7-b065-dedbca814976.png)

**Comment by alextselegidis** [comment]
Please copy config-sample.php to config.php and update it's contents with yours, as stated in the installation guide.

**Comment by edwickensrhenus** [comment]
Hey, I was also a bit stumped by this error - the documentation could be improved by explaining this
https://easyappointments.org/docs.html#1.4.3/docker.md
I was also not expecting to need to install composer and therefore PHP just to run this in a docker container. It seems to me that it would be preferable for these dependencies to be taken care of in the dockerfile - would this be a possibility?

**Comment by edwickensrhenus** [comment]
Managed to get it working with the following Dockerfile:
```
FROM php:7.4-apache

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR "/var/www/html"

COPY  composer.json /var/www/html/
COPY  composer.lock /var/www/html/

RUN  apt-get update && apt-get install -y zip unzip git libpng-dev

RUN docker-php-ext-install gd

RUN composer install --no-scripts --no-interaction --optimize-autoloader

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd gettext mysqli pdo_mysql

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN a2enmod rewrite
```

Due to the location of the dockerfile, I had to copy the composer.json and composer.lock into the same directory to get this working - not desirable, of course, but proves the approach.
I also had to add a volume  `-  /var/www/html/vendor` to the docker-compose.yml to get the vendors/autoload.php created properly. 

I could probably tidy this up to a slightly slicker version - any interest if I do so and create a PR?

**Comment by alextselegidis** [comment]
Thanks for providing your solution @edwickensrhenus, I'll have to check this again and make sure the vendor directory is there. I would also like to update the PHP version to be 8.1 instead of 7.4. You do not have to submit a PR as there are some other items to work on here as well, but thanks for the post. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI there's a new answer on this ticket: 

https://github.com/alextselegidis/easyappointments/issues/1302

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
