### ISSUE TITLE
Multiple Business

### ISSUE THREAD

**Issue by pedropamn** [alextselegidis/easyappointments#851]
There is any way to have multiple business with one installation, when each business has your own user, workers, appointments, etc?

**Comment by alextselegidis** [comment]
Hello @pedropamn 

That requires major core changes that cannot be described here. 

Feel free to get in touch for the creation of a customized build. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
@alextselegidis Are you interested to add this feature to eaysappointments ? If yes, I could try to develop this and submit a PR.

**Comment by alextselegidis** [comment]
Hello @popod, 

This is something that has to be done in a very careful way as it will may interfere with the future services and add-ons that will become available for Easy!Appointments. 

For that I would say that it should be pushed back, so that we can focus on other features and functionality.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
