### ISSUE TITLE
Table calendar issue

### ISSUE THREAD

**Issue by stevewater** [alextselegidis/easyappointments#877]
Hi.

When there are two different appointments at the same time and date, they are displayed as the same one in the table calendar view. When there are more of two appointments at the same time and date, the last two of them are displayed as the same one.

The default calendar view shows them correctly.

![snapshot1](https://user-images.githubusercontent.com/70374650/91553192-48a82280-e92d-11ea-90ec-fe6ffc4386b6.JPG)
![snapshot2](https://user-images.githubusercontent.com/70374650/91553195-4940b900-e92d-11ea-8841-c631400121e8.JPG)

**Comment by alextselegidis** [comment]
Hello! 

This will be fixed with Easy!Appointments v1.4.0

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by pnetherwood** [comment]
I have the same problem. Any pointers to where the issue lies in 1.3.2? I was thinking of doing a temporary fix until 1.4 is out.

**Comment by alextselegidis** [comment]
There is no easy fix for v1.3.2 unfortunately, but in the next couple of days v1.4.0 beta will be released and hopefully soon after v1.4.0 stable will be ready. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
