### ISSUE TITLE
Booking form

### ISSUE THREAD

**Issue by carmelnguyetmy** [alextselegidis/easyappointments#898]
Hi everyone! I have a stuck with booking form. In the default the form has 4 steps. So how can i adding for this form one more step? it's maybe step 5. thank for your answer.

**Comment by alextselegidis** [comment]
Hello! 

The code you need to change is in the book.php and frontend_book.js files. 

In there you will find how the steps are defined and will be able to add your own. 

The steps are dynamically handled so that you will not have to change many hardcoded references. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
