### ISSUE TITLE
REST API: Create appointment not checking availability and attendants number

### ISSUE THREAD

**Issue by nouhouari** [alextselegidis/easyappointments#902]
When using the rest API to create an appointment, the appointment is always created  even if the the provider is not available or if the attendants number is already reached.

**POST** http://localhost/index.php/api/v1/appointments
`
   {
        "start": "2020-10-19 07:30:00",
        "end": "2020-10-19 08:00:00",
        "notes": "Hello world",
        "customerId": 4,
        "providerId": 3,
        "serviceId": 1
    }
`
The returned status code is always 200.

**Comment by alextselegidis** [comment]
Hello! 

Easy!Appointments will not check for availability indeed, because this request simulates the creation of appointments by the admin, which is able to create events any time of the day and even double book. 

If you want to make sure you do not double book, check first for the available hours by calling the availability endpoint. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
