### ISSUE TITLE
REST API: Notification not working when creating/updating/deleting an appointment from the REST API

### ISSUE THREAD

**Issue by nouhouari** [alextselegidis/easyappointments#903]
When creating/updating/deleting an appointment from the REST API, no email notification is sent.

**Comment by nouhouari** [comment]
@alextselegidis What if we create a common service that can be called by both View and Rest API ? This to avoid code duplication.

**Comment by alextselegidis** [comment]
Hello! 

That is indeed an issue as I currently see that changes made by the API will also not be synced. 

I will fix this for v1.4.0 so that it works in sync with the changes made by the view. 

Of course the code will not be duplicated but we'll have common libraries used by both the view and the API. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by nouhouari** [comment]
Please check my PR https://github.com/alextselegidis/easyappointments/pull/906
I will continue to work on continue to change the controller and API.

**Comment by alextselegidis** [comment]
@nouhouari This is now fixed on develop. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by nouhouari** [comment]
Thanks for updating the API. Your implementation is not too far from what I did in my PR but it's cleaner.
You also moved the model loading in the constructor that I guess is better for the performances.
Hope my PR inspired you :-)
