### ISSUE TITLE
User creation endpoint contacted twice

### ISSUE THREAD

**Issue by svenseeberg** [alextselegidis/easyappointments#915]
Easy Appointments version: 1.3.2
PHP version: 7.3
Browser: Firefox 82

When creating any kind of user, two requests to create the user are sent to the AJAX endpoiont, for example `index.php/backend_api/ajax_save_admin`. The first request creates a success message, for example `{"status":"SUCCESS","id":18}`.

The second request throws an error, as the user already exists:
```
{"exceptions":["{\"code\":0,\"file\":\"\\\/var\\\/www\\\/application\\\/models\\\/Admins_model.php\",\"line\":249,\"message\":\"Username already exists. Please select a different username for this record.\",\"previous\":null,\"trace\":\"#0 \\\/var\\\/www\\\/application\\\/models\\\/Admins_model.php(47): Admins_Model->validate(Array)\\n#1 \\\/var\\\/www\\\/application\\\/controllers\\\/Backend_api.php(1142): Admins_Model->add(Array)\\n#2 \\\/var\\\/www\\\/system\\\/core\\\/CodeIgniter.php(532): Backend_api->ajax_save_admin()\\n#3 \\\/var\\\/www\\\/index.php(353): require_once('\\\/var\\\/www\\\/system...')\\n#4 {main}\"}"]}
```

The GUI then shows an error message, that creating the user failed. This, of course, isn't true because the first request succeeded.

**Comment by alextselegidis** [comment]
Hello!

This issue is not present in v1.4.0 

Consider upgrading as soon as the stable release is out (in a few days). 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
