### ISSUE TITLE
1.4Beta - User want create Working Plan Exception

### ISSUE THREAD

**Issue by Fx45** [alextselegidis/easyappointments#927]
Hello 

Thanks a lot for your work and I m very happy to see this new version.
When a user want create Working Plan Exception and particulary a break, I have this message : You do not have the required privileges for this task.

Thanks a lot

**Comment by alextselegidis** [comment]
Hello!

Is this happening with provider and secretary users? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Fx45** [comment]
I only test with provider

**Comment by alextselegidis** [comment]
It's true the providers and secretaries do not have access to the users page. 

In order to change that you can run the following query: 

```
update ea_roles
set users = 15
where id = 2
   or id = 4;
```

This will adjust the permissions in the database. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
