### ISSUE TITLE
Multiple attendant services may lead to double booking.

### ISSUE THREAD

**Issue by Leonex123** [alextselegidis/easyappointments#948]
So i got 1 provider called Tennis and 3 services (tennis 1,tennis 2 and tennis 3)
all 3 services have 3 attendants possbile and are assigned only to 1 provider ,when you book tennis 1 service 3 times at 09:00
system gives you to book tennis 2 at 09:00 and they are services provided by same provider....

**Comment by alextselegidis** [comment]
Hello! 

I could successfully reproduce the problem. 

This will be fixed in v1.4.1, which will be released soon. 

Please do let us know here if you find any additional problems. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
