### ISSUE TITLE
Create an Update timestamp on every data

### ISSUE THREAD

**Issue by DumahBrazorf** [alextselegidis/easyappointments#958]
Hi, 
in order to ease syncronization with external applications it would be useful having a create and an last update timestamp for all data (appointments, services, providers...). Appointments already have the book timestamp but not a last update one.  
In addition who made the creation/last update, via api or web.

**Comment by alextselegidis** [comment]
Hello! 

The database will undergo a heavy round of refactoring in the future but this is something that I'm carefully preparing so that there no problems during the migration towards those new releases. 

For that I'm closing the ticket right now, as the new structure will have creation and modification timestamps. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
