### ISSUE TITLE
Timezone/UX issue: Wrong day is selected when timezone differs by -1 day

### ISSUE THREAD

**Issue by xfxf** [alextselegidis/easyappointments#961]
I have an installation used for booking appointments for an online event.  Some people using the system are from the US (i.e. GMT-8).  I am in GMT +10.5 (Melbourne).

There are two issues when doing this;
 * The UX. A user selects a date (i.e. 17th December).  It defaults to my timezone (+10.5).  User changes to their timezone which is a day earlier (-8).  The date does not change, so user thinks they are selecting a time on the 17th December, but they're actually selecting a date on the 16th Dec.
 * Confirmation screen after booking also has the wrong date (17th Dec) instead of real date, but the email that goes to them has the correct date.

**Comment by alextselegidis** [comment]
All right, that's a use case that is indeed an issue for the visual part. 

It will be fixed in the next version. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by thor432** [comment]
Is it possible to disable web browser timezone, so the site only uses the server/or practitioners timezone?

**Comment by alextselegidis** [comment]
You may adjust the JS file to not automatically switch the the user's timezone. 

Comment the following line out: 

https://github.com/alextselegidis/easyappointments/blob/master/assets/js/frontend_book.js#L133

Make sure you rebuild the assets so that the minified file gets updated too. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by xfxf** [comment]
@alextselegidis this still doesn't seem to be fixe on the latest version - this is reproducable on a plain version of the software, latest version.

I am in Melbourne (GST +10).  The problem exists when somebody tries to book an appointment from the US, which is generally 1 day before us, it leads to massive confusion.

I have overridden some wording (as we're using this to book technical checks for a virtual conference), but the software underneath is vanilla Easy!Appointments.

First, the booking in Sydney time, note 13th:
![image](https://user-images.githubusercontent.com/138684/125367295-399e5780-e3bb-11eb-94de-b96fce9e989e.png)

If this was changed to a US timezone, note it still says the 13th, even though the booking is actually the 12th:

![image](https://user-images.githubusercontent.com/138684/125367370-5fc3f780-e3bb-11eb-8ef9-a14a73c03636.png)

The final confirmation screen says the 13th:
![image](https://user-images.githubusercontent.com/138684/125367471-88e48800-e3bb-11eb-9811-b50ad3ad3e92.png)

But the email says the correct date:
![image](https://user-images.githubusercontent.com/138684/125367588-b92c2680-e3bb-11eb-8ac4-9833cdd59ebf.png)

**Comment by alextselegidis** [comment]
Fixed on develop.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
