### ISSUE TITLE
Secretaries are getting notification emails for providers that are not assigned to them.

### ISSUE THREAD

**Issue by mbaldazzi85** [alextselegidis/easyappointments#966]
When an appointment is made for a provider with secretary and the email notifications are active only for the secretary (not for the provider), an appointment notification email is received also for another provider that has notifications active but which is not connected with the requested provider.
From / admin we have verified that the notification flags are set regularly.
the version used is 1.4.1 stable.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting, this is indeed a bug. 

There's a typo in the notifications library that leads to sending mails to secretaries for providers that are not connected to them, while they do not receive for the providers that are connected.

Will be fixed with the next release, till them you can use the fix of the attached commit. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by RaphaelWimmer** [comment]
This also fixes #262 now.

**Comment by PrDigitus** [comment]
Hi,
I am on 1.4.2 now, but still have the Issue, that Secretary receives no mails.
