### ISSUE TITLE
Problem with making an appointment

### ISSUE THREAD

**Issue by MiisterChipsSs** [alextselegidis/easyappointments#976]
Hello,

After a system installation and configuration, the selection of performance and executing does not work.
Attached is a screen of the site.

Debug mode activate but nothing

![image](https://user-images.githubusercontent.com/36904646/104177720-805dc580-5409-11eb-8255-1d8cec4d3518.png)

**Comment by alextselegidis** [comment]
Hello! 

You will need to have providers and services so that you get options in the booking page. 

It seems you do not have any right now. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by DanSman** [comment]
Hi

I have the same problem.
Just did a fresh install and deleted Jane Doe and the default service (Service). Doesn't matter how many services and provider I add to, it keeps that way like the picture above.

Enable debug mode doesn't show me anything. Nginx or php problem?

**Comment by DanSman** [comment]
Nope. I can't find the problem.

**Comment by alextselegidis** [comment]
Hello @DanSman! 

Easy!Appointments won't show any options in the booking page if you do not have at least one provider that can serve some services. 

For this reason you will need to first create a service, then a provider and then assign the service to that new provider record.

Let us know if this still an issue for you. 

Cheers!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
