### ISSUE TITLE
[ Feature requests]

### ISSUE THREAD

**Issue by AlessioArtini** [alextselegidis/easyappointments#987]
1 - For customers configuration: it shouldn't be mandatory email addresses, if the email is missing system will not send any email notification
2- For backend when adding an appointment: system should show the calendar as showed in frontend and later let me change chosen date/time. So we are sure that the appointment isn't together another one at the same date/time

**Comment by alextselegidis** [comment]
Hello! 

1 - If we do that then duplicate customer entries will be stored to the system, which is in some cases acceptable but not on every case. For this a more sophisticated user system for customers is needed and will be implemented in the future. 

2 - Backend users are able to book in any way they want since they might need to support custom scenarios. This is why there is no validation there. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
