### ISSUE TITLE
Command line sync returning quota error

### ISSUE THREAD

**Issue by sandbergja** [alextselegidis/easyappointments#995]
When I run the command `php index.php console sync`, I get the following error:

    {"message":"{\n  \"error\": {\n    \"code\": 403,\n 
    \"message\": \"Quota exceeded for quota group 'default'
    and limit 'Queries per user per 100 seconds' of service
    'calendar-json.googleapis.com' for consumer
    'project_number:[PROJECT NUMBER]'.\",\n
    \"errors\": [\n      {\n        \"message\": \"Quota exceeded for
    quota group 'default' and limit 'Queries per user per
    100 seconds' of service 'calendar-json.googleapis.com' for 
    consumer '[PROJECT NUMBER]'.\",\n        \"domain\":
    \"usageLimits\",\n        \"reason\":
    \"rateLimitExceeded\"\n      }\n    ],\n
    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n","trace":[]}

We have 7 providers who have Google calendars to sync.

**Comment by alextselegidis** [comment]
Hello! 

There's a limit on how many requests you can make to the Google API service. 

You've reached that limit and thus Google is giving you an error. 

Consider changing the frequency of the syncing task so that you perform less requests during a day, or upgrade your Google Cloud Console account to a premium subscription. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
