### ISSUE TITLE
Can't book multiple times unless is the same service 

### ISSUE THREAD

**Issue by ricapardo** [alextselegidis/easyappointments#997]
I have two attendants for all my services (15min duration all), but I can't book two different services at the same time. Available dates shown are only the ones that are empty or that already have booked the same service I'm trying to book.

**Comment by alextselegidis** [comment]
Hello! 

That's right because the availability is being generated based on the plan of an individual provider (see working plan definition in the app). 

If you need to support simultaneous service bookings then you will need to have a separate provider for each service. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
